package qovery

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/qovery/terraform-provider-qovery/internal/domain/credentials"
)

// Ensure provider defined types fully satisfy terraform framework interfaces.
var _ datasource.DataSourceWithConfigure = &azureCredentialsDataSource{}

type azureCredentialsDataSource struct {
	azureCredentialsService credentials.AzureService
}

func newAzureCredentialsDataSource() datasource.DataSource {
	return &azureCredentialsDataSource{}
}

func (d azureCredentialsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_azure_credentials"
}

func (d *azureCredentialsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	provider, ok := req.ProviderData.(*qProvider)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *qProvider, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	d.azureCredentialsService = provider.azureCredentialsService
}

func (r azureCredentialsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Provides a Qovery Azure credentials data source. This can be used to read existing Qovery Azure credentials. Note: Azure credentials must be created via the Qovery console as the provisioning process requires server-side scripts.",
		MarkdownDescription: "Use this data source to retrieve information about existing Qovery Azure credentials.\n\n" +
			"~> **Important:** Azure credentials **cannot** be created via Terraform. The provisioning process requires server-side scripts that run in the Qovery console. " +
			"Create your Azure credentials in the [Qovery console](https://console.qovery.com) first, then reference them using this data source.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description:         "Id of the Azure credentials.",
				MarkdownDescription: "ID of the Azure credentials to retrieve (UUID format).",
				Required:            true,
			},
			"organization_id": schema.StringAttribute{
				Description:         "Id of the organization.",
				MarkdownDescription: "ID of the organization containing the credentials.",
				Required:            true,
			},
			"name": schema.StringAttribute{
				Description:         "Name of the Azure credentials.",
				MarkdownDescription: "Name of the Azure credentials.",
				Computed:            true,
			},
			"azure_subscription_id": schema.StringAttribute{
				Description:         "Azure subscription ID.",
				MarkdownDescription: "Azure subscription ID associated with these credentials. This is the subscription where AKS clusters will be provisioned.",
				Computed:            true,
			},
			"azure_tenant_id": schema.StringAttribute{
				Description:         "Azure tenant ID.",
				MarkdownDescription: "Azure Active Directory tenant ID associated with these credentials.",
				Computed:            true,
			},
			"azure_application_id": schema.StringAttribute{
				Description:         "Azure application ID (generated by Qovery).",
				MarkdownDescription: "Azure application (client) ID. This is automatically generated by Qovery during the credential provisioning process in the console.",
				Computed:            true,
			},
			"azure_application_object_id": schema.StringAttribute{
				Description:         "Azure application object ID (generated by Qovery).",
				MarkdownDescription: "Azure application object ID. This is automatically generated by Qovery during the credential provisioning process in the console.",
				Computed:            true,
			},
		},
	}
}

// Read qovery azureCredentials data source.
func (d azureCredentialsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	// Get current state
	var data AzureCredentialsDataSource
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Get credentials from API
	creds, err := d.azureCredentialsService.Get(ctx, data.OrganizationId.ValueString(), data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error on azure credentials read", err.Error())
		return
	}

	state := convertDomainAzureCredentialsToDataSource(creds)
	tflog.Trace(ctx, "read azure credentials", map[string]any{"credentials_id": state.Id.ValueString()})

	// Set state
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
