package qovery

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/qovery/terraform-provider-qovery/internal/domain/project"
)

// Ensure provider defined types fully satisfy terraform framework interfaces.
var _ resource.ResourceWithConfigure = &projectResource{}
var _ resource.ResourceWithImportState = projectResource{}

type projectResource struct {
	projectService project.Service
}

func newProjectResource() resource.Resource {
	return &projectResource{}
}

func (r projectResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project"
}

func (r *projectResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	provider, ok := req.ProviderData.(*qProvider)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *qProvider, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.projectService = provider.projectService
}

func (r projectResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Provides a Qovery project resource. This can be used to create and manage Qovery projects. " +
			"A project is a grouping mechanism for environments. Environment variables and secrets defined at the project level are inherited by all environments within the project.",
		MarkdownDescription: "Provides a Qovery project resource. This can be used to create and manage Qovery projects.\n\n" +
			"A project is a grouping mechanism for environments. Environment variables and secrets defined at the project level are inherited by all environments within the project.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description:         "Unique identifier of the project (UUID format).",
				MarkdownDescription: "Unique identifier of the project (UUID format).",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"organization_id": schema.StringAttribute{
				Description:         "Identifier of the organization containing this project (UUID format).",
				MarkdownDescription: "Identifier of the organization containing this project (UUID format).",
				Required:            true,
			},
			"name": schema.StringAttribute{
				Description:         "Name of the project.",
				MarkdownDescription: "Name of the project.",
				Required:            true,
			},
			"description": schema.StringAttribute{
				Description:         "Description of the project.",
				MarkdownDescription: "Description of the project.",
				Optional:            true,
				Computed:            true,
			},
			"built_in_environment_variables": schema.ListNestedAttribute{
				Description:         "List of built-in environment variables linked to this project. Built-in variables are automatically generated by Qovery and provide metadata about the project (e.g., project ID, organization ID).",
				MarkdownDescription: "List of built-in environment variables linked to this project. Built-in variables are automatically generated by Qovery and provide metadata about the project (e.g., project ID, organization ID).",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Description:         "Identifier of the environment variable.",
							MarkdownDescription: "Identifier of the environment variable.",
							Computed:            true,
						},
						"key": schema.StringAttribute{
							Description:         "Key of the environment variable.",
							MarkdownDescription: "Key of the environment variable.",
							Computed:            true,
						},
						"value": schema.StringAttribute{
							Description:         "Value of the environment variable.",
							MarkdownDescription: "Value of the environment variable.",
							Computed:            true,
						},
						"description": schema.StringAttribute{
							Description:         "Description of the environment variable.",
							MarkdownDescription: "Description of the environment variable.",
							Computed:            true,
						},
					},
				},
			},
			"environment_variables": schema.SetNestedAttribute{
				Description:         "Set of environment variables linked to this project. These variables are inherited by all environments within the project.",
				MarkdownDescription: "Set of environment variables linked to this project. These variables are inherited by all environments within the project.",
				Optional:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Description:         "Identifier of the environment variable.",
							MarkdownDescription: "Identifier of the environment variable.",
							Computed:            true,
						},
						"key": schema.StringAttribute{
							Description:         "Key of the environment variable.",
							MarkdownDescription: "Key of the environment variable.",
							Required:            true,
						},
						"value": schema.StringAttribute{
							Description:         "Value of the environment variable.",
							MarkdownDescription: "Value of the environment variable.",
							Required:            true,
						},
						"description": schema.StringAttribute{
							Description:         "Description of the environment variable.",
							MarkdownDescription: "Description of the environment variable.",
							Optional:            true,
						},
					},
				},
			},
			"environment_variable_aliases": schema.SetNestedAttribute{
				Description:         "Set of environment variable aliases linked to this project. An alias creates an alternative name that points to an existing environment variable.",
				MarkdownDescription: "Set of environment variable aliases linked to this project. An alias creates an alternative name that points to an existing environment variable.",
				Optional:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Description:         "Identifier of the environment variable alias.",
							MarkdownDescription: "Identifier of the environment variable alias.",
							Computed:            true,
						},
						"key": schema.StringAttribute{
							Description:         "Name of the alias. This is the new key that will be available as an environment variable.",
							MarkdownDescription: "Name of the alias. This is the new key that will be available as an environment variable.",
							Required:            true,
						},
						"value": schema.StringAttribute{
							Description:         "Name of the variable to alias. Must match the key of an existing environment variable.",
							MarkdownDescription: "Name of the variable to alias. Must match the `key` of an existing environment variable.",
							Required:            true,
						},
						"description": schema.StringAttribute{
							Description:         "Description of the environment variable alias.",
							MarkdownDescription: "Description of the environment variable alias.",
							Optional:            true,
						},
					},
				},
			},
			"secrets": schema.SetNestedAttribute{
				Description:         "Set of secrets linked to this project. Secrets are like environment variables but their values are encrypted and not visible after creation. They are inherited by all environments within the project.",
				MarkdownDescription: "Set of secrets linked to this project. Secrets are like environment variables but their values are encrypted and not visible after creation. They are inherited by all environments within the project.",
				Optional:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Description:         "Identifier of the secret.",
							MarkdownDescription: "Identifier of the secret.",
							Computed:            true,
						},
						"key": schema.StringAttribute{
							Description:         "Key of the secret.",
							MarkdownDescription: "Key of the secret.",
							Required:            true,
						},
						"value": schema.StringAttribute{
							Description:         "Value of the secret. The value is write-only and will not be displayed in plan output.",
							MarkdownDescription: "Value of the secret. The value is write-only and will not be displayed in plan output.",
							Required:            true,
							Sensitive:           true,
						},
						"description": schema.StringAttribute{
							Description:         "Description of the secret.",
							MarkdownDescription: "Description of the secret.",
							Optional:            true,
						},
					},
				},
			},
			"secret_aliases": schema.SetNestedAttribute{
				Description:         "Set of secret aliases linked to this project. An alias creates an alternative name that points to an existing secret.",
				MarkdownDescription: "Set of secret aliases linked to this project. An alias creates an alternative name that points to an existing secret.",
				Optional:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Description:         "Identifier of the secret alias.",
							MarkdownDescription: "Identifier of the secret alias.",
							Computed:            true,
						},
						"key": schema.StringAttribute{
							Description:         "Name of the alias. This is the new key that will be available as a secret.",
							MarkdownDescription: "Name of the alias. This is the new key that will be available as a secret.",
							Required:            true,
						},
						"value": schema.StringAttribute{
							Description:         "Name of the secret to alias. Must match the key of an existing secret.",
							MarkdownDescription: "Name of the secret to alias. Must match the `key` of an existing secret.",
							Required:            true,
						},
						"description": schema.StringAttribute{
							Description:         "Description of the secret alias.",
							MarkdownDescription: "Description of the secret alias.",
							Optional:            true,
						},
					},
				},
			},
		},
	}
}

// Create qovery project resource
func (r projectResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	// Retrieve values from plan
	var plan Project
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Create new project

	proj, err := r.projectService.Create(ctx, plan.OrganizationId.ValueString(), plan.toCreateServiceRequest())
	if err != nil {
		resp.Diagnostics.AddError("Error on project create", err.Error())
		return
	}

	// Initialize state values
	state := convertDomainProjectToProject(ctx, plan, proj)
	tflog.Trace(ctx, "created project", map[string]any{"project_id": state.Id.ValueString()})

	// Set state
	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

// Read qovery project resource
func (r projectResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// Get current state
	var state Project
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Get project from the API
	proj, err := r.projectService.Get(ctx, state.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error on project read", err.Error())
		return
	}

	// Refresh state values
	state = convertDomainProjectToProject(ctx, state, proj)
	tflog.Trace(ctx, "read project", map[string]any{"project_id": state.Id.ValueString()})

	// Set state
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update qovery project resource
func (r projectResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// Get plan and current state
	var plan, state Project
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Update project in the backend
	proj, err := r.projectService.Update(ctx, state.Id.ValueString(), plan.toUpdateServiceRequest(state))
	if err != nil {
		resp.Diagnostics.AddError("Error on project update", err.Error())
		return
	}

	// Update state values
	state = convertDomainProjectToProject(ctx, plan, proj)
	tflog.Trace(ctx, "updated project", map[string]any{"project_id": state.Id.ValueString()})

	// Set state
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Delete qovery project resource
func (r projectResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// Get current state
	var state Project
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Delete project
	err := r.projectService.Delete(ctx, state.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error on project delete", err.Error())
		return
	}

	tflog.Trace(ctx, "deleted project", map[string]any{"project_id": state.Id.ValueString()})

	// Remove project from state
	resp.State.RemoveResource(ctx)
}

// ImportState imports a qovery project resource using its id
func (r projectResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
