run:
  timeout: 60m

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - asciicheck
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - govet
    - ineffassign
    - nakedret
    - misspell
    - staticcheck
    - typecheck
    - unused
    - unconvert
    - unparam
    - whitespace
    - revive
    - gofumpt

linters-settings:
  nakedret:
    max-func-lines: 40
  revive:
    rules:
      - name: var-naming
        disabled: true
