# https://taskfile.dev

version: '3'

vars:
  BINARY_FOLDER: bin
  BINARY_NAME: terraform-provider-qovery
  GOLANGCI_LINT_VERSION: v1.49.0
  MOCKERY_VERSION: v2.14.0

dotenv: ['.env']

tasks:
  mocks:
    desc: Generate mocks for repositories
    deps:
      - install-mockery
    cmds:
      - go generate ./internal/domain/...
    sources:
      - "internal/domain/**/*.go"
      - go.mod
      - go.sum
    generates:
      - internal/application/services/mocks_test/*.go
      - internal/infrastructure/repositories/mocks_test/*.go

  build:
    desc: Build the provider binary
    cmds:
      - go build -v -o {{.BINARY_FOLDER}}/{{.BINARY_NAME}}
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - '{{.BINARY_FOLDER}}/{{.BINARY_NAME}}'

  install:
    deps:
      - install-dev-override
      - build

  test:
    desc: Run unit tests
    cmds:
      - go test -tags=unit -v -cover ./...

  testacc:
    desc: Run acceptance tests
    env:
      TF_ACC: true
    cmds:
      - go test -tags=integration -v -cover -timeout 2h ./...

  docs:
    desc: Update the generated documentation
    cmds:
      - go generate
    sources:
      - "main.go"
      - "qovery/**/*.go"
      - "internal/**/*.go"
      - "examples/**/*.tf"
      - "templates/**/*.tmpl"
      - go.mod
      - go.sum
    generates:
      - docs/**/*.md

  fetch-instance-types:
    desc: Update cluster_instance_types local data
    cmds:
      - ./scripts/fetch_instance_types.sh
    generates:
      - qovery/data/cluster_instance_types/*.json

  lint:
    desc: Run linters
    deps:
      - install-golangci-lint
    cmds:
      - golangci-lint run ./internal/...
    sources:
      - "internal/**/*.go"
      - go.mod
      - go.sum
      - .golangci.yml

  install-golangci-lint:
    desc: Install the golangci-lint tool
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
    status:
      - which golangci-lint
      - golangci-lint version | grep {{.GOLANGCI_LINT_VERSION}}

  install-mockery:
      desc: Install the mockery tool
      cmds:
        - go install github.com/vektra/mockery/v2@{{.MOCKERY_VERSION}}
      status:
        - which mockery
        - mockery --version | grep {{.MOCKERY_VERSION}}

  install-dev-override:
    desc: Set up an override allowing a local version of the provider to be used
    cmds:
      - cmd: |
          cat << EOF > ~/.terraformrc
          provider_installation {
            dev_overrides {
              "qovery/qovery" = "$(pwd)/{{.BINARY_FOLDER}}"
            }
            direct {}
          }
          EOF
    status:
      - cat ~/.terraformrc | grep "$(pwd)/{{.BINARY_FOLDER}}"

  uninstall-dev-override:
    desc: Remove any local terraform overrides for local development
    cmds:
      - rm ~/.terraformrc
