# https://taskfile.dev

version: '3'

vars:
  BINARY_FOLDER: bin
  BINARY_NAME: terraform-provider-qovery
  GOLANGCI_LINT_VERSION: v1.47.3

dotenv: ['.env']

tasks:
  build:
    desc: Build the provider binary
    cmds:
      - go build -v -o {{.BINARY_FOLDER}}/{{.BINARY_NAME}}
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - '{{.BINARY_FOLDER}}/{{.BINARY_NAME}}'

  install:
    deps:
      - install-dev-override
      - build

  test:
    desc: Run acceptance tests
    cmds:
      - go test -v -cover ./... {{.CLI_ARGS}}

  testacc:
    desc: Run acceptance tests
    env:
      TF_ACC: true
    cmds:
      - go test -v -cover -timeout 2h ./... {{.CLI_ARGS}}

  docs:
    desc: Update the generated documentation
    cmds:
      - go generate
    sources:
      - "main.go"
      - "qovery/**/*.go"
      - "examples/**/*.tf"
      - "templates/**/*.tmpl"
      - "qovery/data/cluster_instance_types/*.json"
      - go.mod
      - go.sum
    generates:
      - docs/**/*.md
    deps:
      - fetch-instance-types

  fetch-instance-types:
    desc: Update cluster_instance_types local data
    cmds:
      - ./scripts/fetch_instance_types.sh
    generates:
      - qovery/data/cluster_instance_types/*.json

  lint:
    desc: Run linters
    deps:
      - install-golangci-lint
    cmds:
      - golangci-lint run ./...
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
      - .golangci.yml

  install-golangci-lint:
    desc: Install the golangci-lint tool
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
    status:
      - which golangci-lint
      - golangci-lint version | grep {{.GOLANGCI_LINT_VERSION}}

  install-dev-override:
    desc: Set up an override allowing a local version of the provider to be used
    cmds:
      - cmd: |
          cat << EOF > ~/.terraformrc
          provider_installation {
            dev_overrides {
              "qovery/qovery" = "$(pwd)/{{.BINARY_FOLDER}}"
            }
            direct {}
          }
          EOF
    status:
      - cat ~/.terraformrc | grep "$(pwd)/{{.BINARY_FOLDER}}"

  uninstall-dev-override:
    desc: Remove any local terraform overrides for local development
    cmds:
      - rm ~/.terraformrc