# https://taskfile.dev

version: "3"

vars:
  BINARY_FOLDER: bin
  BINARY_NAME: terraform-provider-qovery
  GOLANGCI_LINT_VERSION: v1.64.8
  MOCKERY_VERSION: v2.53.5
  GOTESTSUM_VERSION: v1.13.0

dotenv: [".env"]

tasks:
  mocks:
    desc: Generate mocks for repositories
    deps:
      - install-mockery
    cmds:
      - go generate ./internal/domain/...
    sources:
      - "internal/domain/**/*.go"
      - go.mod
      - go.sum
    generates:
      - internal/infrastructure/repositories/mocks_test/*.go

  build:
    desc: Build the provider binary
    cmds:
      - go get github.com/qovery/qovery-client-go
      - go build -v -o {{.BINARY_FOLDER}}/{{.BINARY_NAME}}
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BINARY_FOLDER}}/{{.BINARY_NAME}}"

  install:
    deps:
      - install-dev-override
      - build

  test:
    desc: Run unit tests
    deps:
      - install-gotestsum
    cmds:
      - gotestsum --format testdox --jsonfile test-output.json --rerun-fails=2 --packages="./..." -- -tags=unit -cover -timeout 2h -parallel 1

  testacc:
    desc: Run acceptance tests
    deps:
      - install-gotestsum
    env:
      TF_ACC: true
    cmds:
      - gotestsum --format testdox --jsonfile test-output.json --rerun-fails=2 --packages="./..." -- -tags=integration -cover -timeout 2h -parallel 1

  docs:
    desc: Update the generated documentation
    cmds:
      - go generate
    sources:
      - "main.go"
      - "qovery/**/*.go"
      - "internal/**/*.go"
      - "examples/**/*.tf"
      - "examples/**/import.sh"
      - "examples/**/examples.md"
      - "templates/**/*.tmpl"
      - go.mod
      - go.sum
    generates:
      - docs/**/*.md

  fetch-instance-types:
    desc: Update cluster_instance_types local data
    cmds:
      - ./scripts/fetch_instance_types.sh
    generates:
      - qovery/data/cluster_instance_types/*.json

  clean-tests:
    desc: Clean up leftover test resources from Qovery organization
    dir: scripts/cleantests
    cmds:
      - go run main.go

  lint:
    desc: Run linters
    deps:
      - install-golangci-lint
    cmds:
      - golangci-lint run ./internal/...
    sources:
      - "internal/**/*.go"
      - go.mod
      - go.sum
      - .golangci.yml

  install-golangci-lint:
    desc: Install the golangci-lint tool
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
    status:
      - which golangci-lint
      - golangci-lint version | grep {{.GOLANGCI_LINT_VERSION}}

  install-mockery:
    desc: Install the mockery tool
    cmds:
      - go install github.com/vektra/mockery/v2@{{.MOCKERY_VERSION}}
    status:
      - which mockery
      - mockery --version | grep {{.MOCKERY_VERSION}}

  install-gotestsum:
    desc: Install the gotestsum tool
    cmds:
      - go install gotest.tools/gotestsum@{{.GOTESTSUM_VERSION}}
    status:
      - which gotestsum
      - gotestsum --version | grep {{.GOTESTSUM_VERSION}}

  install-dev-override:
    desc: Set up an override allowing a local version of the provider to be used
    cmds:
      - cmd: |
          cat << EOF > ~/.terraformrc
          provider_installation {
            dev_overrides {
              "qovery/qovery" = "$(pwd)/{{.BINARY_FOLDER}}"
            }
            direct {}
          }
          EOF
    status:
      - cat ~/.terraformrc | grep "$(pwd)/{{.BINARY_FOLDER}}"

  uninstall-dev-override:
    desc: Remove any local terraform overrides for local development
    cmds:
      - rm ~/.terraformrc
