// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_test

import (
	context "context"

	status "github.com/qovery/terraform-provider-qovery/internal/domain/status"
	mock "github.com/stretchr/testify/mock"
)

// DeploymentService is an autogenerated mock type for the Service type
type DeploymentService struct {
	mock.Mock
}

type DeploymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *DeploymentService) EXPECT() *DeploymentService_Expecter {
	return &DeploymentService_Expecter{mock: &_m.Mock}
}

// Deploy provides a mock function with given fields: ctx, resourceID, version
func (_m *DeploymentService) Deploy(ctx context.Context, resourceID string, version string) (*status.Status, error) {
	ret := _m.Called(ctx, resourceID, version)

	if len(ret) == 0 {
		panic("no return value specified for Deploy")
	}

	var r0 *status.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*status.Status, error)); ok {
		return rf(ctx, resourceID, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *status.Status); ok {
		r0 = rf(ctx, resourceID, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*status.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, resourceID, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeploymentService_Deploy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deploy'
type DeploymentService_Deploy_Call struct {
	*mock.Call
}

// Deploy is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceID string
//   - version string
func (_e *DeploymentService_Expecter) Deploy(ctx interface{}, resourceID interface{}, version interface{}) *DeploymentService_Deploy_Call {
	return &DeploymentService_Deploy_Call{Call: _e.mock.On("Deploy", ctx, resourceID, version)}
}

func (_c *DeploymentService_Deploy_Call) Run(run func(ctx context.Context, resourceID string, version string)) *DeploymentService_Deploy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *DeploymentService_Deploy_Call) Return(_a0 *status.Status, _a1 error) *DeploymentService_Deploy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeploymentService_Deploy_Call) RunAndReturn(run func(context.Context, string, string) (*status.Status, error)) *DeploymentService_Deploy_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with given fields: ctx, resourceID
func (_m *DeploymentService) GetStatus(ctx context.Context, resourceID string) (*status.Status, error) {
	ret := _m.Called(ctx, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 *status.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*status.Status, error)); ok {
		return rf(ctx, resourceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *status.Status); ok {
		r0 = rf(ctx, resourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*status.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, resourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeploymentService_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type DeploymentService_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceID string
func (_e *DeploymentService_Expecter) GetStatus(ctx interface{}, resourceID interface{}) *DeploymentService_GetStatus_Call {
	return &DeploymentService_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx, resourceID)}
}

func (_c *DeploymentService_GetStatus_Call) Run(run func(ctx context.Context, resourceID string)) *DeploymentService_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DeploymentService_GetStatus_Call) Return(_a0 *status.Status, _a1 error) *DeploymentService_GetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeploymentService_GetStatus_Call) RunAndReturn(run func(context.Context, string) (*status.Status, error)) *DeploymentService_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Redeploy provides a mock function with given fields: ctx, resourceID
func (_m *DeploymentService) Redeploy(ctx context.Context, resourceID string) (*status.Status, error) {
	ret := _m.Called(ctx, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for Redeploy")
	}

	var r0 *status.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*status.Status, error)); ok {
		return rf(ctx, resourceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *status.Status); ok {
		r0 = rf(ctx, resourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*status.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, resourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeploymentService_Redeploy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Redeploy'
type DeploymentService_Redeploy_Call struct {
	*mock.Call
}

// Redeploy is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceID string
func (_e *DeploymentService_Expecter) Redeploy(ctx interface{}, resourceID interface{}) *DeploymentService_Redeploy_Call {
	return &DeploymentService_Redeploy_Call{Call: _e.mock.On("Redeploy", ctx, resourceID)}
}

func (_c *DeploymentService_Redeploy_Call) Run(run func(ctx context.Context, resourceID string)) *DeploymentService_Redeploy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DeploymentService_Redeploy_Call) Return(_a0 *status.Status, _a1 error) *DeploymentService_Redeploy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeploymentService_Redeploy_Call) RunAndReturn(run func(context.Context, string) (*status.Status, error)) *DeploymentService_Redeploy_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields: ctx, resourceID
func (_m *DeploymentService) Stop(ctx context.Context, resourceID string) (*status.Status, error) {
	ret := _m.Called(ctx, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 *status.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*status.Status, error)); ok {
		return rf(ctx, resourceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *status.Status); ok {
		r0 = rf(ctx, resourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*status.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, resourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeploymentService_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type DeploymentService_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceID string
func (_e *DeploymentService_Expecter) Stop(ctx interface{}, resourceID interface{}) *DeploymentService_Stop_Call {
	return &DeploymentService_Stop_Call{Call: _e.mock.On("Stop", ctx, resourceID)}
}

func (_c *DeploymentService_Stop_Call) Run(run func(ctx context.Context, resourceID string)) *DeploymentService_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DeploymentService_Stop_Call) Return(_a0 *status.Status, _a1 error) *DeploymentService_Stop_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeploymentService_Stop_Call) RunAndReturn(run func(context.Context, string) (*status.Status, error)) *DeploymentService_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateState provides a mock function with given fields: ctx, resourceID, desiredState, version
func (_m *DeploymentService) UpdateState(ctx context.Context, resourceID string, desiredState status.State, version string) (*status.Status, error) {
	ret := _m.Called(ctx, resourceID, desiredState, version)

	if len(ret) == 0 {
		panic("no return value specified for UpdateState")
	}

	var r0 *status.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, status.State, string) (*status.Status, error)); ok {
		return rf(ctx, resourceID, desiredState, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, status.State, string) *status.Status); ok {
		r0 = rf(ctx, resourceID, desiredState, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*status.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, status.State, string) error); ok {
		r1 = rf(ctx, resourceID, desiredState, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeploymentService_UpdateState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateState'
type DeploymentService_UpdateState_Call struct {
	*mock.Call
}

// UpdateState is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceID string
//   - desiredState status.State
//   - version string
func (_e *DeploymentService_Expecter) UpdateState(ctx interface{}, resourceID interface{}, desiredState interface{}, version interface{}) *DeploymentService_UpdateState_Call {
	return &DeploymentService_UpdateState_Call{Call: _e.mock.On("UpdateState", ctx, resourceID, desiredState, version)}
}

func (_c *DeploymentService_UpdateState_Call) Run(run func(ctx context.Context, resourceID string, desiredState status.State, version string)) *DeploymentService_UpdateState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(status.State), args[3].(string))
	})
	return _c
}

func (_c *DeploymentService_UpdateState_Call) Return(_a0 *status.Status, _a1 error) *DeploymentService_UpdateState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeploymentService_UpdateState_Call) RunAndReturn(run func(context.Context, string, status.State, string) (*status.Status, error)) *DeploymentService_UpdateState_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeploymentService creates a new instance of DeploymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeploymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeploymentService {
	mock := &DeploymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
