// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks_test

import (
	context "context"

	secret "github.com/qovery/terraform-provider-qovery/internal/domain/secret"
	mock "github.com/stretchr/testify/mock"
)

// SecretService is an autogenerated mock type for the Service type
type SecretService struct {
	mock.Mock
}

type SecretService_Expecter struct {
	mock *mock.Mock
}

func (_m *SecretService) EXPECT() *SecretService_Expecter {
	return &SecretService_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, scopeResourceID
func (_m *SecretService) List(ctx context.Context, scopeResourceID string) (secret.Secrets, error) {
	ret := _m.Called(ctx, scopeResourceID)

	var r0 secret.Secrets
	if rf, ok := ret.Get(0).(func(context.Context, string) secret.Secrets); ok {
		r0 = rf(ctx, scopeResourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(secret.Secrets)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, scopeResourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SecretService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type SecretService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - scopeResourceID string
func (_e *SecretService_Expecter) List(ctx interface{}, scopeResourceID interface{}) *SecretService_List_Call {
	return &SecretService_List_Call{Call: _e.mock.On("List", ctx, scopeResourceID)}
}

func (_c *SecretService_List_Call) Run(run func(ctx context.Context, scopeResourceID string)) *SecretService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SecretService_List_Call) Return(_a0 secret.Secrets, _a1 error) *SecretService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Update provides a mock function with given fields: ctx, scopeResourceID, request
func (_m *SecretService) Update(ctx context.Context, scopeResourceID string, request secret.DiffRequest) (secret.Secrets, error) {
	ret := _m.Called(ctx, scopeResourceID, request)

	var r0 secret.Secrets
	if rf, ok := ret.Get(0).(func(context.Context, string, secret.DiffRequest) secret.Secrets); ok {
		r0 = rf(ctx, scopeResourceID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(secret.Secrets)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, secret.DiffRequest) error); ok {
		r1 = rf(ctx, scopeResourceID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SecretService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type SecretService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - scopeResourceID string
//   - request secret.DiffRequest
func (_e *SecretService_Expecter) Update(ctx interface{}, scopeResourceID interface{}, request interface{}) *SecretService_Update_Call {
	return &SecretService_Update_Call{Call: _e.mock.On("Update", ctx, scopeResourceID, request)}
}

func (_c *SecretService_Update_Call) Run(run func(ctx context.Context, scopeResourceID string, request secret.DiffRequest)) *SecretService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(secret.DiffRequest))
	})
	return _c
}

func (_c *SecretService_Update_Call) Return(_a0 secret.Secrets, _a1 error) *SecretService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewSecretService interface {
	mock.TestingT
	Cleanup(func())
}

// NewSecretService creates a new instance of SecretService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSecretService(t mockConstructorTestingTNewSecretService) *SecretService {
	mock := &SecretService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
