// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_test

import (
	context "context"

	annotations_group "github.com/qovery/terraform-provider-qovery/internal/domain/annotations_group"

	mock "github.com/stretchr/testify/mock"
)

// AnnotationsGroupRepository is an autogenerated mock type for the Repository type
type AnnotationsGroupRepository struct {
	mock.Mock
}

type AnnotationsGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AnnotationsGroupRepository) EXPECT() *AnnotationsGroupRepository_Expecter {
	return &AnnotationsGroupRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, organizationId, request
func (_m *AnnotationsGroupRepository) Create(ctx context.Context, organizationId string, request annotations_group.UpsertRequest) (*annotations_group.AnnotationsGroup, error) {
	ret := _m.Called(ctx, organizationId, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *annotations_group.AnnotationsGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, annotations_group.UpsertRequest) (*annotations_group.AnnotationsGroup, error)); ok {
		return rf(ctx, organizationId, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, annotations_group.UpsertRequest) *annotations_group.AnnotationsGroup); ok {
		r0 = rf(ctx, organizationId, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*annotations_group.AnnotationsGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, annotations_group.UpsertRequest) error); ok {
		r1 = rf(ctx, organizationId, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnnotationsGroupRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AnnotationsGroupRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId string
//   - request annotations_group.UpsertRequest
func (_e *AnnotationsGroupRepository_Expecter) Create(ctx interface{}, organizationId interface{}, request interface{}) *AnnotationsGroupRepository_Create_Call {
	return &AnnotationsGroupRepository_Create_Call{Call: _e.mock.On("Create", ctx, organizationId, request)}
}

func (_c *AnnotationsGroupRepository_Create_Call) Run(run func(ctx context.Context, organizationId string, request annotations_group.UpsertRequest)) *AnnotationsGroupRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(annotations_group.UpsertRequest))
	})
	return _c
}

func (_c *AnnotationsGroupRepository_Create_Call) Return(_a0 *annotations_group.AnnotationsGroup, _a1 error) *AnnotationsGroupRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnnotationsGroupRepository_Create_Call) RunAndReturn(run func(context.Context, string, annotations_group.UpsertRequest) (*annotations_group.AnnotationsGroup, error)) *AnnotationsGroupRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, organizationId, annotationsGroupId
func (_m *AnnotationsGroupRepository) Delete(ctx context.Context, organizationId string, annotationsGroupId string) error {
	ret := _m.Called(ctx, organizationId, annotationsGroupId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, organizationId, annotationsGroupId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AnnotationsGroupRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type AnnotationsGroupRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId string
//   - annotationsGroupId string
func (_e *AnnotationsGroupRepository_Expecter) Delete(ctx interface{}, organizationId interface{}, annotationsGroupId interface{}) *AnnotationsGroupRepository_Delete_Call {
	return &AnnotationsGroupRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, organizationId, annotationsGroupId)}
}

func (_c *AnnotationsGroupRepository_Delete_Call) Run(run func(ctx context.Context, organizationId string, annotationsGroupId string)) *AnnotationsGroupRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AnnotationsGroupRepository_Delete_Call) Return(_a0 error) *AnnotationsGroupRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AnnotationsGroupRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *AnnotationsGroupRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, organizationId, annotationsGroupId
func (_m *AnnotationsGroupRepository) Get(ctx context.Context, organizationId string, annotationsGroupId string) (*annotations_group.AnnotationsGroup, error) {
	ret := _m.Called(ctx, organizationId, annotationsGroupId)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *annotations_group.AnnotationsGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*annotations_group.AnnotationsGroup, error)); ok {
		return rf(ctx, organizationId, annotationsGroupId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *annotations_group.AnnotationsGroup); ok {
		r0 = rf(ctx, organizationId, annotationsGroupId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*annotations_group.AnnotationsGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, organizationId, annotationsGroupId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnnotationsGroupRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type AnnotationsGroupRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId string
//   - annotationsGroupId string
func (_e *AnnotationsGroupRepository_Expecter) Get(ctx interface{}, organizationId interface{}, annotationsGroupId interface{}) *AnnotationsGroupRepository_Get_Call {
	return &AnnotationsGroupRepository_Get_Call{Call: _e.mock.On("Get", ctx, organizationId, annotationsGroupId)}
}

func (_c *AnnotationsGroupRepository_Get_Call) Run(run func(ctx context.Context, organizationId string, annotationsGroupId string)) *AnnotationsGroupRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AnnotationsGroupRepository_Get_Call) Return(_a0 *annotations_group.AnnotationsGroup, _a1 error) *AnnotationsGroupRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnnotationsGroupRepository_Get_Call) RunAndReturn(run func(context.Context, string, string) (*annotations_group.AnnotationsGroup, error)) *AnnotationsGroupRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, organizationId, annotationsGroupId, request
func (_m *AnnotationsGroupRepository) Update(ctx context.Context, organizationId string, annotationsGroupId string, request annotations_group.UpsertRequest) (*annotations_group.AnnotationsGroup, error) {
	ret := _m.Called(ctx, organizationId, annotationsGroupId, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *annotations_group.AnnotationsGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, annotations_group.UpsertRequest) (*annotations_group.AnnotationsGroup, error)); ok {
		return rf(ctx, organizationId, annotationsGroupId, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, annotations_group.UpsertRequest) *annotations_group.AnnotationsGroup); ok {
		r0 = rf(ctx, organizationId, annotationsGroupId, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*annotations_group.AnnotationsGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, annotations_group.UpsertRequest) error); ok {
		r1 = rf(ctx, organizationId, annotationsGroupId, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnnotationsGroupRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type AnnotationsGroupRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId string
//   - annotationsGroupId string
//   - request annotations_group.UpsertRequest
func (_e *AnnotationsGroupRepository_Expecter) Update(ctx interface{}, organizationId interface{}, annotationsGroupId interface{}, request interface{}) *AnnotationsGroupRepository_Update_Call {
	return &AnnotationsGroupRepository_Update_Call{Call: _e.mock.On("Update", ctx, organizationId, annotationsGroupId, request)}
}

func (_c *AnnotationsGroupRepository_Update_Call) Run(run func(ctx context.Context, organizationId string, annotationsGroupId string, request annotations_group.UpsertRequest)) *AnnotationsGroupRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(annotations_group.UpsertRequest))
	})
	return _c
}

func (_c *AnnotationsGroupRepository_Update_Call) Return(_a0 *annotations_group.AnnotationsGroup, _a1 error) *AnnotationsGroupRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnnotationsGroupRepository_Update_Call) RunAndReturn(run func(context.Context, string, string, annotations_group.UpsertRequest) (*annotations_group.AnnotationsGroup, error)) *AnnotationsGroupRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewAnnotationsGroupRepository creates a new instance of AnnotationsGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnnotationsGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnnotationsGroupRepository {
	mock := &AnnotationsGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
