// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_test

import (
	context "context"

	apitoken "github.com/qovery/terraform-provider-qovery/internal/domain/apitoken"
	mock "github.com/stretchr/testify/mock"
)

// ApiTokenRepository is an autogenerated mock type for the Repository type
type ApiTokenRepository struct {
	mock.Mock
}

type ApiTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ApiTokenRepository) EXPECT() *ApiTokenRepository_Expecter {
	return &ApiTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, organizationID, request
func (_m *ApiTokenRepository) Create(ctx context.Context, organizationID string, request apitoken.CreateRequest) (*apitoken.ApiToken, error) {
	ret := _m.Called(ctx, organizationID, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *apitoken.ApiToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, apitoken.CreateRequest) (*apitoken.ApiToken, error)); ok {
		return rf(ctx, organizationID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, apitoken.CreateRequest) *apitoken.ApiToken); ok {
		r0 = rf(ctx, organizationID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apitoken.ApiToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, apitoken.CreateRequest) error); ok {
		r1 = rf(ctx, organizationID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApiTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ApiTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - request apitoken.CreateRequest
func (_e *ApiTokenRepository_Expecter) Create(ctx interface{}, organizationID interface{}, request interface{}) *ApiTokenRepository_Create_Call {
	return &ApiTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, organizationID, request)}
}

func (_c *ApiTokenRepository_Create_Call) Run(run func(ctx context.Context, organizationID string, request apitoken.CreateRequest)) *ApiTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(apitoken.CreateRequest))
	})
	return _c
}

func (_c *ApiTokenRepository_Create_Call) Return(_a0 *apitoken.ApiToken, _a1 error) *ApiTokenRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApiTokenRepository_Create_Call) RunAndReturn(run func(context.Context, string, apitoken.CreateRequest) (*apitoken.ApiToken, error)) *ApiTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, organizationID, apiTokenID
func (_m *ApiTokenRepository) Delete(ctx context.Context, organizationID string, apiTokenID string) error {
	ret := _m.Called(ctx, organizationID, apiTokenID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, organizationID, apiTokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ApiTokenRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ApiTokenRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - apiTokenID string
func (_e *ApiTokenRepository_Expecter) Delete(ctx interface{}, organizationID interface{}, apiTokenID interface{}) *ApiTokenRepository_Delete_Call {
	return &ApiTokenRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, organizationID, apiTokenID)}
}

func (_c *ApiTokenRepository_Delete_Call) Run(run func(ctx context.Context, organizationID string, apiTokenID string)) *ApiTokenRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ApiTokenRepository_Delete_Call) Return(_a0 error) *ApiTokenRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ApiTokenRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *ApiTokenRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, organizationID, apiTokenID
func (_m *ApiTokenRepository) Get(ctx context.Context, organizationID string, apiTokenID string) (*apitoken.ApiToken, error) {
	ret := _m.Called(ctx, organizationID, apiTokenID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *apitoken.ApiToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*apitoken.ApiToken, error)); ok {
		return rf(ctx, organizationID, apiTokenID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *apitoken.ApiToken); ok {
		r0 = rf(ctx, organizationID, apiTokenID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apitoken.ApiToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, organizationID, apiTokenID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApiTokenRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ApiTokenRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - apiTokenID string
func (_e *ApiTokenRepository_Expecter) Get(ctx interface{}, organizationID interface{}, apiTokenID interface{}) *ApiTokenRepository_Get_Call {
	return &ApiTokenRepository_Get_Call{Call: _e.mock.On("Get", ctx, organizationID, apiTokenID)}
}

func (_c *ApiTokenRepository_Get_Call) Run(run func(ctx context.Context, organizationID string, apiTokenID string)) *ApiTokenRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ApiTokenRepository_Get_Call) Return(_a0 *apitoken.ApiToken, _a1 error) *ApiTokenRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ApiTokenRepository_Get_Call) RunAndReturn(run func(context.Context, string, string) (*apitoken.ApiToken, error)) *ApiTokenRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewApiTokenRepository creates a new instance of ApiTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApiTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApiTokenRepository {
	mock := &ApiTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
