// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_test

import (
	context "context"

	argoCdCredentials "github.com/qovery/terraform-provider-qovery/internal/domain/argoCdCredentials"
	mock "github.com/stretchr/testify/mock"
)

// ArgoCdCredentialsRepository is an autogenerated mock type for the Repository type
type ArgoCdCredentialsRepository struct {
	mock.Mock
}

type ArgoCdCredentialsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ArgoCdCredentialsRepository) EXPECT() *ArgoCdCredentialsRepository_Expecter {
	return &ArgoCdCredentialsRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, clusterID, request
func (_m *ArgoCdCredentialsRepository) Create(ctx context.Context, clusterID string, request argoCdCredentials.UpsertRequest) (*argoCdCredentials.ArgoCdCredentials, error) {
	ret := _m.Called(ctx, clusterID, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *argoCdCredentials.ArgoCdCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, argoCdCredentials.UpsertRequest) (*argoCdCredentials.ArgoCdCredentials, error)); ok {
		return rf(ctx, clusterID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, argoCdCredentials.UpsertRequest) *argoCdCredentials.ArgoCdCredentials); ok {
		r0 = rf(ctx, clusterID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*argoCdCredentials.ArgoCdCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, argoCdCredentials.UpsertRequest) error); ok {
		r1 = rf(ctx, clusterID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ArgoCdCredentialsRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ArgoCdCredentialsRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
//   - request argoCdCredentials.UpsertRequest
func (_e *ArgoCdCredentialsRepository_Expecter) Create(ctx interface{}, clusterID interface{}, request interface{}) *ArgoCdCredentialsRepository_Create_Call {
	return &ArgoCdCredentialsRepository_Create_Call{Call: _e.mock.On("Create", ctx, clusterID, request)}
}

func (_c *ArgoCdCredentialsRepository_Create_Call) Run(run func(ctx context.Context, clusterID string, request argoCdCredentials.UpsertRequest)) *ArgoCdCredentialsRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(argoCdCredentials.UpsertRequest))
	})
	return _c
}

func (_c *ArgoCdCredentialsRepository_Create_Call) Return(_a0 *argoCdCredentials.ArgoCdCredentials, _a1 error) *ArgoCdCredentialsRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ArgoCdCredentialsRepository_Create_Call) RunAndReturn(run func(context.Context, string, argoCdCredentials.UpsertRequest) (*argoCdCredentials.ArgoCdCredentials, error)) *ArgoCdCredentialsRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, clusterID
func (_m *ArgoCdCredentialsRepository) Delete(ctx context.Context, clusterID string) error {
	ret := _m.Called(ctx, clusterID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, clusterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArgoCdCredentialsRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ArgoCdCredentialsRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
func (_e *ArgoCdCredentialsRepository_Expecter) Delete(ctx interface{}, clusterID interface{}) *ArgoCdCredentialsRepository_Delete_Call {
	return &ArgoCdCredentialsRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, clusterID)}
}

func (_c *ArgoCdCredentialsRepository_Delete_Call) Run(run func(ctx context.Context, clusterID string)) *ArgoCdCredentialsRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ArgoCdCredentialsRepository_Delete_Call) Return(_a0 error) *ArgoCdCredentialsRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArgoCdCredentialsRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *ArgoCdCredentialsRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, clusterID
func (_m *ArgoCdCredentialsRepository) Get(ctx context.Context, clusterID string) (*argoCdCredentials.ArgoCdCredentials, error) {
	ret := _m.Called(ctx, clusterID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *argoCdCredentials.ArgoCdCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*argoCdCredentials.ArgoCdCredentials, error)); ok {
		return rf(ctx, clusterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *argoCdCredentials.ArgoCdCredentials); ok {
		r0 = rf(ctx, clusterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*argoCdCredentials.ArgoCdCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clusterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ArgoCdCredentialsRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ArgoCdCredentialsRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
func (_e *ArgoCdCredentialsRepository_Expecter) Get(ctx interface{}, clusterID interface{}) *ArgoCdCredentialsRepository_Get_Call {
	return &ArgoCdCredentialsRepository_Get_Call{Call: _e.mock.On("Get", ctx, clusterID)}
}

func (_c *ArgoCdCredentialsRepository_Get_Call) Run(run func(ctx context.Context, clusterID string)) *ArgoCdCredentialsRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ArgoCdCredentialsRepository_Get_Call) Return(_a0 *argoCdCredentials.ArgoCdCredentials, _a1 error) *ArgoCdCredentialsRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ArgoCdCredentialsRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*argoCdCredentials.ArgoCdCredentials, error)) *ArgoCdCredentialsRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, clusterID, request
func (_m *ArgoCdCredentialsRepository) Update(ctx context.Context, clusterID string, request argoCdCredentials.UpsertRequest) (*argoCdCredentials.ArgoCdCredentials, error) {
	ret := _m.Called(ctx, clusterID, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *argoCdCredentials.ArgoCdCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, argoCdCredentials.UpsertRequest) (*argoCdCredentials.ArgoCdCredentials, error)); ok {
		return rf(ctx, clusterID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, argoCdCredentials.UpsertRequest) *argoCdCredentials.ArgoCdCredentials); ok {
		r0 = rf(ctx, clusterID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*argoCdCredentials.ArgoCdCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, argoCdCredentials.UpsertRequest) error); ok {
		r1 = rf(ctx, clusterID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ArgoCdCredentialsRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ArgoCdCredentialsRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
//   - request argoCdCredentials.UpsertRequest
func (_e *ArgoCdCredentialsRepository_Expecter) Update(ctx interface{}, clusterID interface{}, request interface{}) *ArgoCdCredentialsRepository_Update_Call {
	return &ArgoCdCredentialsRepository_Update_Call{Call: _e.mock.On("Update", ctx, clusterID, request)}
}

func (_c *ArgoCdCredentialsRepository_Update_Call) Run(run func(ctx context.Context, clusterID string, request argoCdCredentials.UpsertRequest)) *ArgoCdCredentialsRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(argoCdCredentials.UpsertRequest))
	})
	return _c
}

func (_c *ArgoCdCredentialsRepository_Update_Call) Return(_a0 *argoCdCredentials.ArgoCdCredentials, _a1 error) *ArgoCdCredentialsRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ArgoCdCredentialsRepository_Update_Call) RunAndReturn(run func(context.Context, string, argoCdCredentials.UpsertRequest) (*argoCdCredentials.ArgoCdCredentials, error)) *ArgoCdCredentialsRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewArgoCdCredentialsRepository creates a new instance of ArgoCdCredentialsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArgoCdCredentialsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArgoCdCredentialsRepository {
	mock := &ArgoCdCredentialsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
