// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_test

import (
	context "context"

	argoCdDestinationClusterMapping "github.com/qovery/terraform-provider-qovery/internal/domain/argoCdDestinationClusterMapping"
	mock "github.com/stretchr/testify/mock"
)

// ArgoCdDestinationClusterMappingRepository is an autogenerated mock type for the Repository type
type ArgoCdDestinationClusterMappingRepository struct {
	mock.Mock
}

type ArgoCdDestinationClusterMappingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ArgoCdDestinationClusterMappingRepository) EXPECT() *ArgoCdDestinationClusterMappingRepository_Expecter {
	return &ArgoCdDestinationClusterMappingRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, orgID, request
func (_m *ArgoCdDestinationClusterMappingRepository) Create(ctx context.Context, orgID string, request argoCdDestinationClusterMapping.UpsertRequest) (*argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping, error) {
	ret := _m.Called(ctx, orgID, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, argoCdDestinationClusterMapping.UpsertRequest) (*argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping, error)); ok {
		return rf(ctx, orgID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, argoCdDestinationClusterMapping.UpsertRequest) *argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping); ok {
		r0 = rf(ctx, orgID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, argoCdDestinationClusterMapping.UpsertRequest) error); ok {
		r1 = rf(ctx, orgID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ArgoCdDestinationClusterMappingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ArgoCdDestinationClusterMappingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - request argoCdDestinationClusterMapping.UpsertRequest
func (_e *ArgoCdDestinationClusterMappingRepository_Expecter) Create(ctx interface{}, orgID interface{}, request interface{}) *ArgoCdDestinationClusterMappingRepository_Create_Call {
	return &ArgoCdDestinationClusterMappingRepository_Create_Call{Call: _e.mock.On("Create", ctx, orgID, request)}
}

func (_c *ArgoCdDestinationClusterMappingRepository_Create_Call) Run(run func(ctx context.Context, orgID string, request argoCdDestinationClusterMapping.UpsertRequest)) *ArgoCdDestinationClusterMappingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(argoCdDestinationClusterMapping.UpsertRequest))
	})
	return _c
}

func (_c *ArgoCdDestinationClusterMappingRepository_Create_Call) Return(_a0 *argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping, _a1 error) *ArgoCdDestinationClusterMappingRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ArgoCdDestinationClusterMappingRepository_Create_Call) RunAndReturn(run func(context.Context, string, argoCdDestinationClusterMapping.UpsertRequest) (*argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping, error)) *ArgoCdDestinationClusterMappingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, orgID, agentClusterID, argocdClusterUrl
func (_m *ArgoCdDestinationClusterMappingRepository) Delete(ctx context.Context, orgID string, agentClusterID string, argocdClusterUrl string) error {
	ret := _m.Called(ctx, orgID, agentClusterID, argocdClusterUrl)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, orgID, agentClusterID, argocdClusterUrl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArgoCdDestinationClusterMappingRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ArgoCdDestinationClusterMappingRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - agentClusterID string
//   - argocdClusterUrl string
func (_e *ArgoCdDestinationClusterMappingRepository_Expecter) Delete(ctx interface{}, orgID interface{}, agentClusterID interface{}, argocdClusterUrl interface{}) *ArgoCdDestinationClusterMappingRepository_Delete_Call {
	return &ArgoCdDestinationClusterMappingRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, orgID, agentClusterID, argocdClusterUrl)}
}

func (_c *ArgoCdDestinationClusterMappingRepository_Delete_Call) Run(run func(ctx context.Context, orgID string, agentClusterID string, argocdClusterUrl string)) *ArgoCdDestinationClusterMappingRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ArgoCdDestinationClusterMappingRepository_Delete_Call) Return(_a0 error) *ArgoCdDestinationClusterMappingRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArgoCdDestinationClusterMappingRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string, string) error) *ArgoCdDestinationClusterMappingRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, orgID, agentClusterID, argocdClusterUrl
func (_m *ArgoCdDestinationClusterMappingRepository) Get(ctx context.Context, orgID string, agentClusterID string, argocdClusterUrl string) (*argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping, error) {
	ret := _m.Called(ctx, orgID, agentClusterID, argocdClusterUrl)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping, error)); ok {
		return rf(ctx, orgID, agentClusterID, argocdClusterUrl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping); ok {
		r0 = rf(ctx, orgID, agentClusterID, argocdClusterUrl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, orgID, agentClusterID, argocdClusterUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ArgoCdDestinationClusterMappingRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ArgoCdDestinationClusterMappingRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - agentClusterID string
//   - argocdClusterUrl string
func (_e *ArgoCdDestinationClusterMappingRepository_Expecter) Get(ctx interface{}, orgID interface{}, agentClusterID interface{}, argocdClusterUrl interface{}) *ArgoCdDestinationClusterMappingRepository_Get_Call {
	return &ArgoCdDestinationClusterMappingRepository_Get_Call{Call: _e.mock.On("Get", ctx, orgID, agentClusterID, argocdClusterUrl)}
}

func (_c *ArgoCdDestinationClusterMappingRepository_Get_Call) Run(run func(ctx context.Context, orgID string, agentClusterID string, argocdClusterUrl string)) *ArgoCdDestinationClusterMappingRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ArgoCdDestinationClusterMappingRepository_Get_Call) Return(_a0 *argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping, _a1 error) *ArgoCdDestinationClusterMappingRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ArgoCdDestinationClusterMappingRepository_Get_Call) RunAndReturn(run func(context.Context, string, string, string) (*argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping, error)) *ArgoCdDestinationClusterMappingRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, orgID, request
func (_m *ArgoCdDestinationClusterMappingRepository) Update(ctx context.Context, orgID string, request argoCdDestinationClusterMapping.UpsertRequest) (*argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping, error) {
	ret := _m.Called(ctx, orgID, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, argoCdDestinationClusterMapping.UpsertRequest) (*argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping, error)); ok {
		return rf(ctx, orgID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, argoCdDestinationClusterMapping.UpsertRequest) *argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping); ok {
		r0 = rf(ctx, orgID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, argoCdDestinationClusterMapping.UpsertRequest) error); ok {
		r1 = rf(ctx, orgID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ArgoCdDestinationClusterMappingRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ArgoCdDestinationClusterMappingRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - request argoCdDestinationClusterMapping.UpsertRequest
func (_e *ArgoCdDestinationClusterMappingRepository_Expecter) Update(ctx interface{}, orgID interface{}, request interface{}) *ArgoCdDestinationClusterMappingRepository_Update_Call {
	return &ArgoCdDestinationClusterMappingRepository_Update_Call{Call: _e.mock.On("Update", ctx, orgID, request)}
}

func (_c *ArgoCdDestinationClusterMappingRepository_Update_Call) Run(run func(ctx context.Context, orgID string, request argoCdDestinationClusterMapping.UpsertRequest)) *ArgoCdDestinationClusterMappingRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(argoCdDestinationClusterMapping.UpsertRequest))
	})
	return _c
}

func (_c *ArgoCdDestinationClusterMappingRepository_Update_Call) Return(_a0 *argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping, _a1 error) *ArgoCdDestinationClusterMappingRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ArgoCdDestinationClusterMappingRepository_Update_Call) RunAndReturn(run func(context.Context, string, argoCdDestinationClusterMapping.UpsertRequest) (*argoCdDestinationClusterMapping.ArgoCdDestinationClusterMapping, error)) *ArgoCdDestinationClusterMappingRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewArgoCdDestinationClusterMappingRepository creates a new instance of ArgoCdDestinationClusterMappingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArgoCdDestinationClusterMappingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArgoCdDestinationClusterMappingRepository {
	mock := &ArgoCdDestinationClusterMappingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
