// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_test

import (
	context "context"

	blueprint "github.com/qovery/terraform-provider-qovery/internal/domain/blueprint"
	mock "github.com/stretchr/testify/mock"
)

// BlueprintRepository is an autogenerated mock type for the Repository type
type BlueprintRepository struct {
	mock.Mock
}

type BlueprintRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BlueprintRepository) EXPECT() *BlueprintRepository_Expecter {
	return &BlueprintRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, environmentID, request
func (_m *BlueprintRepository) Create(ctx context.Context, environmentID string, request blueprint.CreateRequest) (*blueprint.CreationResult, error) {
	ret := _m.Called(ctx, environmentID, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *blueprint.CreationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, blueprint.CreateRequest) (*blueprint.CreationResult, error)); ok {
		return rf(ctx, environmentID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, blueprint.CreateRequest) *blueprint.CreationResult); ok {
		r0 = rf(ctx, environmentID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*blueprint.CreationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, blueprint.CreateRequest) error); ok {
		r1 = rf(ctx, environmentID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlueprintRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type BlueprintRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - environmentID string
//   - request blueprint.CreateRequest
func (_e *BlueprintRepository_Expecter) Create(ctx interface{}, environmentID interface{}, request interface{}) *BlueprintRepository_Create_Call {
	return &BlueprintRepository_Create_Call{Call: _e.mock.On("Create", ctx, environmentID, request)}
}

func (_c *BlueprintRepository_Create_Call) Run(run func(ctx context.Context, environmentID string, request blueprint.CreateRequest)) *BlueprintRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(blueprint.CreateRequest))
	})
	return _c
}

func (_c *BlueprintRepository_Create_Call) Return(_a0 *blueprint.CreationResult, _a1 error) *BlueprintRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlueprintRepository_Create_Call) RunAndReturn(run func(context.Context, string, blueprint.CreateRequest) (*blueprint.CreationResult, error)) *BlueprintRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteService provides a mock function with given fields: ctx, serviceType, serviceID
func (_m *BlueprintRepository) DeleteService(ctx context.Context, serviceType blueprint.ServiceType, serviceID string) (bool, error) {
	ret := _m.Called(ctx, serviceType, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteService")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, blueprint.ServiceType, string) (bool, error)); ok {
		return rf(ctx, serviceType, serviceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, blueprint.ServiceType, string) bool); ok {
		r0 = rf(ctx, serviceType, serviceID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, blueprint.ServiceType, string) error); ok {
		r1 = rf(ctx, serviceType, serviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlueprintRepository_DeleteService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteService'
type BlueprintRepository_DeleteService_Call struct {
	*mock.Call
}

// DeleteService is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceType blueprint.ServiceType
//   - serviceID string
func (_e *BlueprintRepository_Expecter) DeleteService(ctx interface{}, serviceType interface{}, serviceID interface{}) *BlueprintRepository_DeleteService_Call {
	return &BlueprintRepository_DeleteService_Call{Call: _e.mock.On("DeleteService", ctx, serviceType, serviceID)}
}

func (_c *BlueprintRepository_DeleteService_Call) Run(run func(ctx context.Context, serviceType blueprint.ServiceType, serviceID string)) *BlueprintRepository_DeleteService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(blueprint.ServiceType), args[2].(string))
	})
	return _c
}

func (_c *BlueprintRepository_DeleteService_Call) Return(_a0 bool, _a1 error) *BlueprintRepository_DeleteService_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlueprintRepository_DeleteService_Call) RunAndReturn(run func(context.Context, blueprint.ServiceType, string) (bool, error)) *BlueprintRepository_DeleteService_Call {
	_c.Call.Return(run)
	return _c
}

// Deploy provides a mock function with given fields: ctx, blueprintID
func (_m *BlueprintRepository) Deploy(ctx context.Context, blueprintID string) (string, error) {
	ret := _m.Called(ctx, blueprintID)

	if len(ret) == 0 {
		panic("no return value specified for Deploy")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, blueprintID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, blueprintID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, blueprintID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlueprintRepository_Deploy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deploy'
type BlueprintRepository_Deploy_Call struct {
	*mock.Call
}

// Deploy is a helper method to define mock.On call
//   - ctx context.Context
//   - blueprintID string
func (_e *BlueprintRepository_Expecter) Deploy(ctx interface{}, blueprintID interface{}) *BlueprintRepository_Deploy_Call {
	return &BlueprintRepository_Deploy_Call{Call: _e.mock.On("Deploy", ctx, blueprintID)}
}

func (_c *BlueprintRepository_Deploy_Call) Run(run func(ctx context.Context, blueprintID string)) *BlueprintRepository_Deploy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BlueprintRepository_Deploy_Call) Return(_a0 string, _a1 error) *BlueprintRepository_Deploy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlueprintRepository_Deploy_Call) RunAndReturn(run func(context.Context, string) (string, error)) *BlueprintRepository_Deploy_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, blueprintID
func (_m *BlueprintRepository) Get(ctx context.Context, blueprintID string) (*blueprint.Blueprint, error) {
	ret := _m.Called(ctx, blueprintID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *blueprint.Blueprint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*blueprint.Blueprint, error)); ok {
		return rf(ctx, blueprintID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *blueprint.Blueprint); ok {
		r0 = rf(ctx, blueprintID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*blueprint.Blueprint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, blueprintID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlueprintRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type BlueprintRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - blueprintID string
func (_e *BlueprintRepository_Expecter) Get(ctx interface{}, blueprintID interface{}) *BlueprintRepository_Get_Call {
	return &BlueprintRepository_Get_Call{Call: _e.mock.On("Get", ctx, blueprintID)}
}

func (_c *BlueprintRepository_Get_Call) Run(run func(ctx context.Context, blueprintID string)) *BlueprintRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BlueprintRepository_Get_Call) Return(_a0 *blueprint.Blueprint, _a1 error) *BlueprintRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlueprintRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*blueprint.Blueprint, error)) *BlueprintRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationID provides a mock function with given fields: ctx, environmentID
func (_m *BlueprintRepository) GetOrganizationID(ctx context.Context, environmentID string) (string, error) {
	ret := _m.Called(ctx, environmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, environmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, environmentID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, environmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlueprintRepository_GetOrganizationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationID'
type BlueprintRepository_GetOrganizationID_Call struct {
	*mock.Call
}

// GetOrganizationID is a helper method to define mock.On call
//   - ctx context.Context
//   - environmentID string
func (_e *BlueprintRepository_Expecter) GetOrganizationID(ctx interface{}, environmentID interface{}) *BlueprintRepository_GetOrganizationID_Call {
	return &BlueprintRepository_GetOrganizationID_Call{Call: _e.mock.On("GetOrganizationID", ctx, environmentID)}
}

func (_c *BlueprintRepository_GetOrganizationID_Call) Run(run func(ctx context.Context, environmentID string)) *BlueprintRepository_GetOrganizationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BlueprintRepository_GetOrganizationID_Call) Return(_a0 string, _a1 error) *BlueprintRepository_GetOrganizationID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlueprintRepository_GetOrganizationID_Call) RunAndReturn(run func(context.Context, string) (string, error)) *BlueprintRepository_GetOrganizationID_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceStatus provides a mock function with given fields: ctx, environmentID, serviceType, serviceID
func (_m *BlueprintRepository) GetServiceStatus(ctx context.Context, environmentID string, serviceType blueprint.ServiceType, serviceID string) (*blueprint.ServiceStatus, error) {
	ret := _m.Called(ctx, environmentID, serviceType, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceStatus")
	}

	var r0 *blueprint.ServiceStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, blueprint.ServiceType, string) (*blueprint.ServiceStatus, error)); ok {
		return rf(ctx, environmentID, serviceType, serviceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, blueprint.ServiceType, string) *blueprint.ServiceStatus); ok {
		r0 = rf(ctx, environmentID, serviceType, serviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*blueprint.ServiceStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, blueprint.ServiceType, string) error); ok {
		r1 = rf(ctx, environmentID, serviceType, serviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlueprintRepository_GetServiceStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceStatus'
type BlueprintRepository_GetServiceStatus_Call struct {
	*mock.Call
}

// GetServiceStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - environmentID string
//   - serviceType blueprint.ServiceType
//   - serviceID string
func (_e *BlueprintRepository_Expecter) GetServiceStatus(ctx interface{}, environmentID interface{}, serviceType interface{}, serviceID interface{}) *BlueprintRepository_GetServiceStatus_Call {
	return &BlueprintRepository_GetServiceStatus_Call{Call: _e.mock.On("GetServiceStatus", ctx, environmentID, serviceType, serviceID)}
}

func (_c *BlueprintRepository_GetServiceStatus_Call) Run(run func(ctx context.Context, environmentID string, serviceType blueprint.ServiceType, serviceID string)) *BlueprintRepository_GetServiceStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(blueprint.ServiceType), args[3].(string))
	})
	return _c
}

func (_c *BlueprintRepository_GetServiceStatus_Call) Return(_a0 *blueprint.ServiceStatus, _a1 error) *BlueprintRepository_GetServiceStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlueprintRepository_GetServiceStatus_Call) RunAndReturn(run func(context.Context, string, blueprint.ServiceType, string) (*blueprint.ServiceStatus, error)) *BlueprintRepository_GetServiceStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ListCatalog provides a mock function with given fields: ctx, organizationID
func (_m *BlueprintRepository) ListCatalog(ctx context.Context, organizationID string) ([]blueprint.CatalogEntry, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListCatalog")
	}

	var r0 []blueprint.CatalogEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]blueprint.CatalogEntry, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []blueprint.CatalogEntry); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]blueprint.CatalogEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlueprintRepository_ListCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCatalog'
type BlueprintRepository_ListCatalog_Call struct {
	*mock.Call
}

// ListCatalog is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
func (_e *BlueprintRepository_Expecter) ListCatalog(ctx interface{}, organizationID interface{}) *BlueprintRepository_ListCatalog_Call {
	return &BlueprintRepository_ListCatalog_Call{Call: _e.mock.On("ListCatalog", ctx, organizationID)}
}

func (_c *BlueprintRepository_ListCatalog_Call) Run(run func(ctx context.Context, organizationID string)) *BlueprintRepository_ListCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BlueprintRepository_ListCatalog_Call) Return(_a0 []blueprint.CatalogEntry, _a1 error) *BlueprintRepository_ListCatalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlueprintRepository_ListCatalog_Call) RunAndReturn(run func(context.Context, string) ([]blueprint.CatalogEntry, error)) *BlueprintRepository_ListCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, blueprintID, request
func (_m *BlueprintRepository) Update(ctx context.Context, blueprintID string, request blueprint.UpdateRequest) error {
	ret := _m.Called(ctx, blueprintID, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, blueprint.UpdateRequest) error); ok {
		r0 = rf(ctx, blueprintID, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BlueprintRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type BlueprintRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - blueprintID string
//   - request blueprint.UpdateRequest
func (_e *BlueprintRepository_Expecter) Update(ctx interface{}, blueprintID interface{}, request interface{}) *BlueprintRepository_Update_Call {
	return &BlueprintRepository_Update_Call{Call: _e.mock.On("Update", ctx, blueprintID, request)}
}

func (_c *BlueprintRepository_Update_Call) Run(run func(ctx context.Context, blueprintID string, request blueprint.UpdateRequest)) *BlueprintRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(blueprint.UpdateRequest))
	})
	return _c
}

func (_c *BlueprintRepository_Update_Call) Return(_a0 error) *BlueprintRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BlueprintRepository_Update_Call) RunAndReturn(run func(context.Context, string, blueprint.UpdateRequest) error) *BlueprintRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewBlueprintRepository creates a new instance of BlueprintRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlueprintRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlueprintRepository {
	mock := &BlueprintRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
