// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_test

import (
	context "context"

	credentials "github.com/qovery/terraform-provider-qovery/internal/domain/credentials"
	mock "github.com/stretchr/testify/mock"
)

// CredentialsGcpRepository is an autogenerated mock type for the GcpRepository type
type CredentialsGcpRepository struct {
	mock.Mock
}

type CredentialsGcpRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CredentialsGcpRepository) EXPECT() *CredentialsGcpRepository_Expecter {
	return &CredentialsGcpRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, organizationID, request
func (_m *CredentialsGcpRepository) Create(ctx context.Context, organizationID string, request credentials.UpsertGcpRequest) (*credentials.Credentials, error) {
	ret := _m.Called(ctx, organizationID, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *credentials.Credentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, credentials.UpsertGcpRequest) (*credentials.Credentials, error)); ok {
		return rf(ctx, organizationID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, credentials.UpsertGcpRequest) *credentials.Credentials); ok {
		r0 = rf(ctx, organizationID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*credentials.Credentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, credentials.UpsertGcpRequest) error); ok {
		r1 = rf(ctx, organizationID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CredentialsGcpRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CredentialsGcpRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - request credentials.UpsertGcpRequest
func (_e *CredentialsGcpRepository_Expecter) Create(ctx interface{}, organizationID interface{}, request interface{}) *CredentialsGcpRepository_Create_Call {
	return &CredentialsGcpRepository_Create_Call{Call: _e.mock.On("Create", ctx, organizationID, request)}
}

func (_c *CredentialsGcpRepository_Create_Call) Run(run func(ctx context.Context, organizationID string, request credentials.UpsertGcpRequest)) *CredentialsGcpRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(credentials.UpsertGcpRequest))
	})
	return _c
}

func (_c *CredentialsGcpRepository_Create_Call) Return(_a0 *credentials.Credentials, _a1 error) *CredentialsGcpRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CredentialsGcpRepository_Create_Call) RunAndReturn(run func(context.Context, string, credentials.UpsertGcpRequest) (*credentials.Credentials, error)) *CredentialsGcpRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, organizationID, credentialsID
func (_m *CredentialsGcpRepository) Delete(ctx context.Context, organizationID string, credentialsID string) error {
	ret := _m.Called(ctx, organizationID, credentialsID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, organizationID, credentialsID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CredentialsGcpRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CredentialsGcpRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - credentialsID string
func (_e *CredentialsGcpRepository_Expecter) Delete(ctx interface{}, organizationID interface{}, credentialsID interface{}) *CredentialsGcpRepository_Delete_Call {
	return &CredentialsGcpRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, organizationID, credentialsID)}
}

func (_c *CredentialsGcpRepository_Delete_Call) Run(run func(ctx context.Context, organizationID string, credentialsID string)) *CredentialsGcpRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CredentialsGcpRepository_Delete_Call) Return(_a0 error) *CredentialsGcpRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CredentialsGcpRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *CredentialsGcpRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, organizationID, credentialsID
func (_m *CredentialsGcpRepository) Get(ctx context.Context, organizationID string, credentialsID string) (*credentials.Credentials, error) {
	ret := _m.Called(ctx, organizationID, credentialsID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *credentials.Credentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*credentials.Credentials, error)); ok {
		return rf(ctx, organizationID, credentialsID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *credentials.Credentials); ok {
		r0 = rf(ctx, organizationID, credentialsID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*credentials.Credentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, organizationID, credentialsID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CredentialsGcpRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CredentialsGcpRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - credentialsID string
func (_e *CredentialsGcpRepository_Expecter) Get(ctx interface{}, organizationID interface{}, credentialsID interface{}) *CredentialsGcpRepository_Get_Call {
	return &CredentialsGcpRepository_Get_Call{Call: _e.mock.On("Get", ctx, organizationID, credentialsID)}
}

func (_c *CredentialsGcpRepository_Get_Call) Run(run func(ctx context.Context, organizationID string, credentialsID string)) *CredentialsGcpRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CredentialsGcpRepository_Get_Call) Return(_a0 *credentials.Credentials, _a1 error) *CredentialsGcpRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CredentialsGcpRepository_Get_Call) RunAndReturn(run func(context.Context, string, string) (*credentials.Credentials, error)) *CredentialsGcpRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, organizationID, credentialsID, request
func (_m *CredentialsGcpRepository) Update(ctx context.Context, organizationID string, credentialsID string, request credentials.UpsertGcpRequest) (*credentials.Credentials, error) {
	ret := _m.Called(ctx, organizationID, credentialsID, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *credentials.Credentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, credentials.UpsertGcpRequest) (*credentials.Credentials, error)); ok {
		return rf(ctx, organizationID, credentialsID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, credentials.UpsertGcpRequest) *credentials.Credentials); ok {
		r0 = rf(ctx, organizationID, credentialsID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*credentials.Credentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, credentials.UpsertGcpRequest) error); ok {
		r1 = rf(ctx, organizationID, credentialsID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CredentialsGcpRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CredentialsGcpRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - credentialsID string
//   - request credentials.UpsertGcpRequest
func (_e *CredentialsGcpRepository_Expecter) Update(ctx interface{}, organizationID interface{}, credentialsID interface{}, request interface{}) *CredentialsGcpRepository_Update_Call {
	return &CredentialsGcpRepository_Update_Call{Call: _e.mock.On("Update", ctx, organizationID, credentialsID, request)}
}

func (_c *CredentialsGcpRepository_Update_Call) Run(run func(ctx context.Context, organizationID string, credentialsID string, request credentials.UpsertGcpRequest)) *CredentialsGcpRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(credentials.UpsertGcpRequest))
	})
	return _c
}

func (_c *CredentialsGcpRepository_Update_Call) Return(_a0 *credentials.Credentials, _a1 error) *CredentialsGcpRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CredentialsGcpRepository_Update_Call) RunAndReturn(run func(context.Context, string, string, credentials.UpsertGcpRequest) (*credentials.Credentials, error)) *CredentialsGcpRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCredentialsGcpRepository creates a new instance of CredentialsGcpRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialsGcpRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialsGcpRepository {
	mock := &CredentialsGcpRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
