// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks_test

import (
	context "context"

	credentials "github.com/qovery/terraform-provider-qovery/internal/domain/credentials"
	mock "github.com/stretchr/testify/mock"
)

// CredentialsScalewayRepository is an autogenerated mock type for the ScalewayRepository type
type CredentialsScalewayRepository struct {
	mock.Mock
}

type CredentialsScalewayRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CredentialsScalewayRepository) EXPECT() *CredentialsScalewayRepository_Expecter {
	return &CredentialsScalewayRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, organizationID, request
func (_m *CredentialsScalewayRepository) Create(ctx context.Context, organizationID string, request credentials.UpsertScalewayRequest) (*credentials.Credentials, error) {
	ret := _m.Called(ctx, organizationID, request)

	var r0 *credentials.Credentials
	if rf, ok := ret.Get(0).(func(context.Context, string, credentials.UpsertScalewayRequest) *credentials.Credentials); ok {
		r0 = rf(ctx, organizationID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*credentials.Credentials)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, credentials.UpsertScalewayRequest) error); ok {
		r1 = rf(ctx, organizationID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CredentialsScalewayRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CredentialsScalewayRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//  - ctx context.Context
//  - organizationID string
//  - request credentials.UpsertScalewayRequest
func (_e *CredentialsScalewayRepository_Expecter) Create(ctx interface{}, organizationID interface{}, request interface{}) *CredentialsScalewayRepository_Create_Call {
	return &CredentialsScalewayRepository_Create_Call{Call: _e.mock.On("Create", ctx, organizationID, request)}
}

func (_c *CredentialsScalewayRepository_Create_Call) Run(run func(ctx context.Context, organizationID string, request credentials.UpsertScalewayRequest)) *CredentialsScalewayRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(credentials.UpsertScalewayRequest))
	})
	return _c
}

func (_c *CredentialsScalewayRepository_Create_Call) Return(_a0 *credentials.Credentials, _a1 error) *CredentialsScalewayRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Delete provides a mock function with given fields: ctx, organizationID, credentialsID
func (_m *CredentialsScalewayRepository) Delete(ctx context.Context, organizationID string, credentialsID string) error {
	ret := _m.Called(ctx, organizationID, credentialsID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, organizationID, credentialsID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CredentialsScalewayRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CredentialsScalewayRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//  - ctx context.Context
//  - organizationID string
//  - credentialsID string
func (_e *CredentialsScalewayRepository_Expecter) Delete(ctx interface{}, organizationID interface{}, credentialsID interface{}) *CredentialsScalewayRepository_Delete_Call {
	return &CredentialsScalewayRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, organizationID, credentialsID)}
}

func (_c *CredentialsScalewayRepository_Delete_Call) Run(run func(ctx context.Context, organizationID string, credentialsID string)) *CredentialsScalewayRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CredentialsScalewayRepository_Delete_Call) Return(_a0 error) *CredentialsScalewayRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

// Get provides a mock function with given fields: ctx, organizationID, credentialsID
func (_m *CredentialsScalewayRepository) Get(ctx context.Context, organizationID string, credentialsID string) (*credentials.Credentials, error) {
	ret := _m.Called(ctx, organizationID, credentialsID)

	var r0 *credentials.Credentials
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *credentials.Credentials); ok {
		r0 = rf(ctx, organizationID, credentialsID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*credentials.Credentials)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, organizationID, credentialsID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CredentialsScalewayRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CredentialsScalewayRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//  - ctx context.Context
//  - organizationID string
//  - credentialsID string
func (_e *CredentialsScalewayRepository_Expecter) Get(ctx interface{}, organizationID interface{}, credentialsID interface{}) *CredentialsScalewayRepository_Get_Call {
	return &CredentialsScalewayRepository_Get_Call{Call: _e.mock.On("Get", ctx, organizationID, credentialsID)}
}

func (_c *CredentialsScalewayRepository_Get_Call) Run(run func(ctx context.Context, organizationID string, credentialsID string)) *CredentialsScalewayRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CredentialsScalewayRepository_Get_Call) Return(_a0 *credentials.Credentials, _a1 error) *CredentialsScalewayRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Update provides a mock function with given fields: ctx, organizationID, credentialsID, request
func (_m *CredentialsScalewayRepository) Update(ctx context.Context, organizationID string, credentialsID string, request credentials.UpsertScalewayRequest) (*credentials.Credentials, error) {
	ret := _m.Called(ctx, organizationID, credentialsID, request)

	var r0 *credentials.Credentials
	if rf, ok := ret.Get(0).(func(context.Context, string, string, credentials.UpsertScalewayRequest) *credentials.Credentials); ok {
		r0 = rf(ctx, organizationID, credentialsID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*credentials.Credentials)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, credentials.UpsertScalewayRequest) error); ok {
		r1 = rf(ctx, organizationID, credentialsID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CredentialsScalewayRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CredentialsScalewayRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//  - ctx context.Context
//  - organizationID string
//  - credentialsID string
//  - request credentials.UpsertScalewayRequest
func (_e *CredentialsScalewayRepository_Expecter) Update(ctx interface{}, organizationID interface{}, credentialsID interface{}, request interface{}) *CredentialsScalewayRepository_Update_Call {
	return &CredentialsScalewayRepository_Update_Call{Call: _e.mock.On("Update", ctx, organizationID, credentialsID, request)}
}

func (_c *CredentialsScalewayRepository_Update_Call) Run(run func(ctx context.Context, organizationID string, credentialsID string, request credentials.UpsertScalewayRequest)) *CredentialsScalewayRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(credentials.UpsertScalewayRequest))
	})
	return _c
}

func (_c *CredentialsScalewayRepository_Update_Call) Return(_a0 *credentials.Credentials, _a1 error) *CredentialsScalewayRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewCredentialsScalewayRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewCredentialsScalewayRepository creates a new instance of CredentialsScalewayRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCredentialsScalewayRepository(t mockConstructorTestingTNewCredentialsScalewayRepository) *CredentialsScalewayRepository {
	mock := &CredentialsScalewayRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
