// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_test

import (
	context "context"

	customrole "github.com/qovery/terraform-provider-qovery/internal/domain/customrole"
	mock "github.com/stretchr/testify/mock"
)

// CustomRoleRepository is an autogenerated mock type for the Repository type
type CustomRoleRepository struct {
	mock.Mock
}

type CustomRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomRoleRepository) EXPECT() *CustomRoleRepository_Expecter {
	return &CustomRoleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, organizationID, request
func (_m *CustomRoleRepository) Create(ctx context.Context, organizationID string, request customrole.UpsertRequest) (*customrole.CustomRole, error) {
	ret := _m.Called(ctx, organizationID, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *customrole.CustomRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, customrole.UpsertRequest) (*customrole.CustomRole, error)); ok {
		return rf(ctx, organizationID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, customrole.UpsertRequest) *customrole.CustomRole); ok {
		r0 = rf(ctx, organizationID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customrole.CustomRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, customrole.UpsertRequest) error); ok {
		r1 = rf(ctx, organizationID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CustomRoleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CustomRoleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - request customrole.UpsertRequest
func (_e *CustomRoleRepository_Expecter) Create(ctx interface{}, organizationID interface{}, request interface{}) *CustomRoleRepository_Create_Call {
	return &CustomRoleRepository_Create_Call{Call: _e.mock.On("Create", ctx, organizationID, request)}
}

func (_c *CustomRoleRepository_Create_Call) Run(run func(ctx context.Context, organizationID string, request customrole.UpsertRequest)) *CustomRoleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(customrole.UpsertRequest))
	})
	return _c
}

func (_c *CustomRoleRepository_Create_Call) Return(_a0 *customrole.CustomRole, _a1 error) *CustomRoleRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CustomRoleRepository_Create_Call) RunAndReturn(run func(context.Context, string, customrole.UpsertRequest) (*customrole.CustomRole, error)) *CustomRoleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, organizationID, customRoleID
func (_m *CustomRoleRepository) Delete(ctx context.Context, organizationID string, customRoleID string) error {
	ret := _m.Called(ctx, organizationID, customRoleID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, organizationID, customRoleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomRoleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CustomRoleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - customRoleID string
func (_e *CustomRoleRepository_Expecter) Delete(ctx interface{}, organizationID interface{}, customRoleID interface{}) *CustomRoleRepository_Delete_Call {
	return &CustomRoleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, organizationID, customRoleID)}
}

func (_c *CustomRoleRepository_Delete_Call) Run(run func(ctx context.Context, organizationID string, customRoleID string)) *CustomRoleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CustomRoleRepository_Delete_Call) Return(_a0 error) *CustomRoleRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomRoleRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *CustomRoleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, organizationID, customRoleID
func (_m *CustomRoleRepository) Get(ctx context.Context, organizationID string, customRoleID string) (*customrole.CustomRole, error) {
	ret := _m.Called(ctx, organizationID, customRoleID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *customrole.CustomRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*customrole.CustomRole, error)); ok {
		return rf(ctx, organizationID, customRoleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *customrole.CustomRole); ok {
		r0 = rf(ctx, organizationID, customRoleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customrole.CustomRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, organizationID, customRoleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CustomRoleRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CustomRoleRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - customRoleID string
func (_e *CustomRoleRepository_Expecter) Get(ctx interface{}, organizationID interface{}, customRoleID interface{}) *CustomRoleRepository_Get_Call {
	return &CustomRoleRepository_Get_Call{Call: _e.mock.On("Get", ctx, organizationID, customRoleID)}
}

func (_c *CustomRoleRepository_Get_Call) Run(run func(ctx context.Context, organizationID string, customRoleID string)) *CustomRoleRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CustomRoleRepository_Get_Call) Return(_a0 *customrole.CustomRole, _a1 error) *CustomRoleRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CustomRoleRepository_Get_Call) RunAndReturn(run func(context.Context, string, string) (*customrole.CustomRole, error)) *CustomRoleRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, organizationID, customRoleID, request
func (_m *CustomRoleRepository) Update(ctx context.Context, organizationID string, customRoleID string, request customrole.UpsertRequest) (*customrole.CustomRole, error) {
	ret := _m.Called(ctx, organizationID, customRoleID, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *customrole.CustomRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, customrole.UpsertRequest) (*customrole.CustomRole, error)); ok {
		return rf(ctx, organizationID, customRoleID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, customrole.UpsertRequest) *customrole.CustomRole); ok {
		r0 = rf(ctx, organizationID, customRoleID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customrole.CustomRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, customrole.UpsertRequest) error); ok {
		r1 = rf(ctx, organizationID, customRoleID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CustomRoleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CustomRoleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - customRoleID string
//   - request customrole.UpsertRequest
func (_e *CustomRoleRepository_Expecter) Update(ctx interface{}, organizationID interface{}, customRoleID interface{}, request interface{}) *CustomRoleRepository_Update_Call {
	return &CustomRoleRepository_Update_Call{Call: _e.mock.On("Update", ctx, organizationID, customRoleID, request)}
}

func (_c *CustomRoleRepository_Update_Call) Run(run func(ctx context.Context, organizationID string, customRoleID string, request customrole.UpsertRequest)) *CustomRoleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(customrole.UpsertRequest))
	})
	return _c
}

func (_c *CustomRoleRepository_Update_Call) Return(_a0 *customrole.CustomRole, _a1 error) *CustomRoleRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CustomRoleRepository_Update_Call) RunAndReturn(run func(context.Context, string, string, customrole.UpsertRequest) (*customrole.CustomRole, error)) *CustomRoleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCustomRoleRepository creates a new instance of CustomRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomRoleRepository {
	mock := &CustomRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
