// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_test

import (
	context "context"

	deploymentstage "github.com/qovery/terraform-provider-qovery/internal/domain/deploymentstage"
	mock "github.com/stretchr/testify/mock"
)

// DeploymentStageRepository is an autogenerated mock type for the Repository type
type DeploymentStageRepository struct {
	mock.Mock
}

type DeploymentStageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DeploymentStageRepository) EXPECT() *DeploymentStageRepository_Expecter {
	return &DeploymentStageRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, environmentID, request
func (_m *DeploymentStageRepository) Create(ctx context.Context, environmentID string, request deploymentstage.UpsertRepositoryRequest) (*deploymentstage.DeploymentStage, error) {
	ret := _m.Called(ctx, environmentID, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *deploymentstage.DeploymentStage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, deploymentstage.UpsertRepositoryRequest) (*deploymentstage.DeploymentStage, error)); ok {
		return rf(ctx, environmentID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, deploymentstage.UpsertRepositoryRequest) *deploymentstage.DeploymentStage); ok {
		r0 = rf(ctx, environmentID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*deploymentstage.DeploymentStage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, deploymentstage.UpsertRepositoryRequest) error); ok {
		r1 = rf(ctx, environmentID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeploymentStageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type DeploymentStageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - environmentID string
//   - request deploymentstage.UpsertRepositoryRequest
func (_e *DeploymentStageRepository_Expecter) Create(ctx interface{}, environmentID interface{}, request interface{}) *DeploymentStageRepository_Create_Call {
	return &DeploymentStageRepository_Create_Call{Call: _e.mock.On("Create", ctx, environmentID, request)}
}

func (_c *DeploymentStageRepository_Create_Call) Run(run func(ctx context.Context, environmentID string, request deploymentstage.UpsertRepositoryRequest)) *DeploymentStageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(deploymentstage.UpsertRepositoryRequest))
	})
	return _c
}

func (_c *DeploymentStageRepository_Create_Call) Return(_a0 *deploymentstage.DeploymentStage, _a1 error) *DeploymentStageRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeploymentStageRepository_Create_Call) RunAndReturn(run func(context.Context, string, deploymentstage.UpsertRepositoryRequest) (*deploymentstage.DeploymentStage, error)) *DeploymentStageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, deploymentStageID
func (_m *DeploymentStageRepository) Delete(ctx context.Context, deploymentStageID string) error {
	ret := _m.Called(ctx, deploymentStageID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, deploymentStageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeploymentStageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type DeploymentStageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentStageID string
func (_e *DeploymentStageRepository_Expecter) Delete(ctx interface{}, deploymentStageID interface{}) *DeploymentStageRepository_Delete_Call {
	return &DeploymentStageRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, deploymentStageID)}
}

func (_c *DeploymentStageRepository_Delete_Call) Run(run func(ctx context.Context, deploymentStageID string)) *DeploymentStageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DeploymentStageRepository_Delete_Call) Return(_a0 error) *DeploymentStageRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeploymentStageRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *DeploymentStageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, environmentID, deploymentStageID
func (_m *DeploymentStageRepository) Get(ctx context.Context, environmentID string, deploymentStageID string) (*deploymentstage.DeploymentStage, error) {
	ret := _m.Called(ctx, environmentID, deploymentStageID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *deploymentstage.DeploymentStage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*deploymentstage.DeploymentStage, error)); ok {
		return rf(ctx, environmentID, deploymentStageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *deploymentstage.DeploymentStage); ok {
		r0 = rf(ctx, environmentID, deploymentStageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*deploymentstage.DeploymentStage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, environmentID, deploymentStageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeploymentStageRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type DeploymentStageRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - environmentID string
//   - deploymentStageID string
func (_e *DeploymentStageRepository_Expecter) Get(ctx interface{}, environmentID interface{}, deploymentStageID interface{}) *DeploymentStageRepository_Get_Call {
	return &DeploymentStageRepository_Get_Call{Call: _e.mock.On("Get", ctx, environmentID, deploymentStageID)}
}

func (_c *DeploymentStageRepository_Get_Call) Run(run func(ctx context.Context, environmentID string, deploymentStageID string)) *DeploymentStageRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *DeploymentStageRepository_Get_Call) Return(_a0 *deploymentstage.DeploymentStage, _a1 error) *DeploymentStageRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeploymentStageRepository_Get_Call) RunAndReturn(run func(context.Context, string, string) (*deploymentstage.DeploymentStage, error)) *DeploymentStageRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByEnvironmentID provides a mock function with given fields: ctx, environmentID
func (_m *DeploymentStageRepository) GetAllByEnvironmentID(ctx context.Context, environmentID string) (*[]deploymentstage.DeploymentStage, error) {
	ret := _m.Called(ctx, environmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByEnvironmentID")
	}

	var r0 *[]deploymentstage.DeploymentStage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*[]deploymentstage.DeploymentStage, error)); ok {
		return rf(ctx, environmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *[]deploymentstage.DeploymentStage); ok {
		r0 = rf(ctx, environmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]deploymentstage.DeploymentStage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, environmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeploymentStageRepository_GetAllByEnvironmentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByEnvironmentID'
type DeploymentStageRepository_GetAllByEnvironmentID_Call struct {
	*mock.Call
}

// GetAllByEnvironmentID is a helper method to define mock.On call
//   - ctx context.Context
//   - environmentID string
func (_e *DeploymentStageRepository_Expecter) GetAllByEnvironmentID(ctx interface{}, environmentID interface{}) *DeploymentStageRepository_GetAllByEnvironmentID_Call {
	return &DeploymentStageRepository_GetAllByEnvironmentID_Call{Call: _e.mock.On("GetAllByEnvironmentID", ctx, environmentID)}
}

func (_c *DeploymentStageRepository_GetAllByEnvironmentID_Call) Run(run func(ctx context.Context, environmentID string)) *DeploymentStageRepository_GetAllByEnvironmentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DeploymentStageRepository_GetAllByEnvironmentID_Call) Return(_a0 *[]deploymentstage.DeploymentStage, _a1 error) *DeploymentStageRepository_GetAllByEnvironmentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeploymentStageRepository_GetAllByEnvironmentID_Call) RunAndReturn(run func(context.Context, string) (*[]deploymentstage.DeploymentStage, error)) *DeploymentStageRepository_GetAllByEnvironmentID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, deploymentStageID, request
func (_m *DeploymentStageRepository) Update(ctx context.Context, deploymentStageID string, request deploymentstage.UpsertRepositoryRequest) (*deploymentstage.DeploymentStage, error) {
	ret := _m.Called(ctx, deploymentStageID, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *deploymentstage.DeploymentStage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, deploymentstage.UpsertRepositoryRequest) (*deploymentstage.DeploymentStage, error)); ok {
		return rf(ctx, deploymentStageID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, deploymentstage.UpsertRepositoryRequest) *deploymentstage.DeploymentStage); ok {
		r0 = rf(ctx, deploymentStageID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*deploymentstage.DeploymentStage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, deploymentstage.UpsertRepositoryRequest) error); ok {
		r1 = rf(ctx, deploymentStageID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeploymentStageRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type DeploymentStageRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentStageID string
//   - request deploymentstage.UpsertRepositoryRequest
func (_e *DeploymentStageRepository_Expecter) Update(ctx interface{}, deploymentStageID interface{}, request interface{}) *DeploymentStageRepository_Update_Call {
	return &DeploymentStageRepository_Update_Call{Call: _e.mock.On("Update", ctx, deploymentStageID, request)}
}

func (_c *DeploymentStageRepository_Update_Call) Run(run func(ctx context.Context, deploymentStageID string, request deploymentstage.UpsertRepositoryRequest)) *DeploymentStageRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(deploymentstage.UpsertRepositoryRequest))
	})
	return _c
}

func (_c *DeploymentStageRepository_Update_Call) Return(_a0 *deploymentstage.DeploymentStage, _a1 error) *DeploymentStageRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeploymentStageRepository_Update_Call) RunAndReturn(run func(context.Context, string, deploymentstage.UpsertRepositoryRequest) (*deploymentstage.DeploymentStage, error)) *DeploymentStageRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeploymentStageRepository creates a new instance of DeploymentStageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeploymentStageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeploymentStageRepository {
	mock := &DeploymentStageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
