// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_test

import (
	context "context"

	helmRepository "github.com/qovery/terraform-provider-qovery/internal/domain/helmRepository"
	mock "github.com/stretchr/testify/mock"
)

// HelmRepositoryRepository is an autogenerated mock type for the Repository type
type HelmRepositoryRepository struct {
	mock.Mock
}

type HelmRepositoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *HelmRepositoryRepository) EXPECT() *HelmRepositoryRepository_Expecter {
	return &HelmRepositoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, organizationID, request
func (_m *HelmRepositoryRepository) Create(ctx context.Context, organizationID string, request helmRepository.UpsertRequest) (*helmRepository.HelmRepository, error) {
	ret := _m.Called(ctx, organizationID, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *helmRepository.HelmRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, helmRepository.UpsertRequest) (*helmRepository.HelmRepository, error)); ok {
		return rf(ctx, organizationID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, helmRepository.UpsertRequest) *helmRepository.HelmRepository); ok {
		r0 = rf(ctx, organizationID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*helmRepository.HelmRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, helmRepository.UpsertRequest) error); ok {
		r1 = rf(ctx, organizationID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HelmRepositoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type HelmRepositoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - request helmRepository.UpsertRequest
func (_e *HelmRepositoryRepository_Expecter) Create(ctx interface{}, organizationID interface{}, request interface{}) *HelmRepositoryRepository_Create_Call {
	return &HelmRepositoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, organizationID, request)}
}

func (_c *HelmRepositoryRepository_Create_Call) Run(run func(ctx context.Context, organizationID string, request helmRepository.UpsertRequest)) *HelmRepositoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(helmRepository.UpsertRequest))
	})
	return _c
}

func (_c *HelmRepositoryRepository_Create_Call) Return(_a0 *helmRepository.HelmRepository, _a1 error) *HelmRepositoryRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HelmRepositoryRepository_Create_Call) RunAndReturn(run func(context.Context, string, helmRepository.UpsertRequest) (*helmRepository.HelmRepository, error)) *HelmRepositoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, organizationID, registryID
func (_m *HelmRepositoryRepository) Delete(ctx context.Context, organizationID string, registryID string) error {
	ret := _m.Called(ctx, organizationID, registryID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, organizationID, registryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HelmRepositoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type HelmRepositoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - registryID string
func (_e *HelmRepositoryRepository_Expecter) Delete(ctx interface{}, organizationID interface{}, registryID interface{}) *HelmRepositoryRepository_Delete_Call {
	return &HelmRepositoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, organizationID, registryID)}
}

func (_c *HelmRepositoryRepository_Delete_Call) Run(run func(ctx context.Context, organizationID string, registryID string)) *HelmRepositoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *HelmRepositoryRepository_Delete_Call) Return(_a0 error) *HelmRepositoryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HelmRepositoryRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *HelmRepositoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, organizationID, registryID
func (_m *HelmRepositoryRepository) Get(ctx context.Context, organizationID string, registryID string) (*helmRepository.HelmRepository, error) {
	ret := _m.Called(ctx, organizationID, registryID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *helmRepository.HelmRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*helmRepository.HelmRepository, error)); ok {
		return rf(ctx, organizationID, registryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *helmRepository.HelmRepository); ok {
		r0 = rf(ctx, organizationID, registryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*helmRepository.HelmRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, organizationID, registryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HelmRepositoryRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type HelmRepositoryRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - registryID string
func (_e *HelmRepositoryRepository_Expecter) Get(ctx interface{}, organizationID interface{}, registryID interface{}) *HelmRepositoryRepository_Get_Call {
	return &HelmRepositoryRepository_Get_Call{Call: _e.mock.On("Get", ctx, organizationID, registryID)}
}

func (_c *HelmRepositoryRepository_Get_Call) Run(run func(ctx context.Context, organizationID string, registryID string)) *HelmRepositoryRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *HelmRepositoryRepository_Get_Call) Return(_a0 *helmRepository.HelmRepository, _a1 error) *HelmRepositoryRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HelmRepositoryRepository_Get_Call) RunAndReturn(run func(context.Context, string, string) (*helmRepository.HelmRepository, error)) *HelmRepositoryRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, organizationID, registryID, request
func (_m *HelmRepositoryRepository) Update(ctx context.Context, organizationID string, registryID string, request helmRepository.UpsertRequest) (*helmRepository.HelmRepository, error) {
	ret := _m.Called(ctx, organizationID, registryID, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *helmRepository.HelmRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, helmRepository.UpsertRequest) (*helmRepository.HelmRepository, error)); ok {
		return rf(ctx, organizationID, registryID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, helmRepository.UpsertRequest) *helmRepository.HelmRepository); ok {
		r0 = rf(ctx, organizationID, registryID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*helmRepository.HelmRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, helmRepository.UpsertRequest) error); ok {
		r1 = rf(ctx, organizationID, registryID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HelmRepositoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type HelmRepositoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - registryID string
//   - request helmRepository.UpsertRequest
func (_e *HelmRepositoryRepository_Expecter) Update(ctx interface{}, organizationID interface{}, registryID interface{}, request interface{}) *HelmRepositoryRepository_Update_Call {
	return &HelmRepositoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, organizationID, registryID, request)}
}

func (_c *HelmRepositoryRepository_Update_Call) Run(run func(ctx context.Context, organizationID string, registryID string, request helmRepository.UpsertRequest)) *HelmRepositoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(helmRepository.UpsertRequest))
	})
	return _c
}

func (_c *HelmRepositoryRepository_Update_Call) Return(_a0 *helmRepository.HelmRepository, _a1 error) *HelmRepositoryRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HelmRepositoryRepository_Update_Call) RunAndReturn(run func(context.Context, string, string, helmRepository.UpsertRequest) (*helmRepository.HelmRepository, error)) *HelmRepositoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewHelmRepositoryRepository creates a new instance of HelmRepositoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHelmRepositoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *HelmRepositoryRepository {
	mock := &HelmRepositoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
