// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_test

import (
	context "context"

	labels_group "github.com/qovery/terraform-provider-qovery/internal/domain/labels_group"
	mock "github.com/stretchr/testify/mock"
)

// LabelsGroupRepository is an autogenerated mock type for the Repository type
type LabelsGroupRepository struct {
	mock.Mock
}

type LabelsGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *LabelsGroupRepository) EXPECT() *LabelsGroupRepository_Expecter {
	return &LabelsGroupRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, organizationId, request
func (_m *LabelsGroupRepository) Create(ctx context.Context, organizationId string, request labels_group.UpsertRequest) (*labels_group.LabelsGroup, error) {
	ret := _m.Called(ctx, organizationId, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *labels_group.LabelsGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, labels_group.UpsertRequest) (*labels_group.LabelsGroup, error)); ok {
		return rf(ctx, organizationId, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, labels_group.UpsertRequest) *labels_group.LabelsGroup); ok {
		r0 = rf(ctx, organizationId, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*labels_group.LabelsGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, labels_group.UpsertRequest) error); ok {
		r1 = rf(ctx, organizationId, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LabelsGroupRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type LabelsGroupRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId string
//   - request labels_group.UpsertRequest
func (_e *LabelsGroupRepository_Expecter) Create(ctx interface{}, organizationId interface{}, request interface{}) *LabelsGroupRepository_Create_Call {
	return &LabelsGroupRepository_Create_Call{Call: _e.mock.On("Create", ctx, organizationId, request)}
}

func (_c *LabelsGroupRepository_Create_Call) Run(run func(ctx context.Context, organizationId string, request labels_group.UpsertRequest)) *LabelsGroupRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(labels_group.UpsertRequest))
	})
	return _c
}

func (_c *LabelsGroupRepository_Create_Call) Return(_a0 *labels_group.LabelsGroup, _a1 error) *LabelsGroupRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LabelsGroupRepository_Create_Call) RunAndReturn(run func(context.Context, string, labels_group.UpsertRequest) (*labels_group.LabelsGroup, error)) *LabelsGroupRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, organizationId, labelsGroupId
func (_m *LabelsGroupRepository) Delete(ctx context.Context, organizationId string, labelsGroupId string) error {
	ret := _m.Called(ctx, organizationId, labelsGroupId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, organizationId, labelsGroupId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LabelsGroupRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type LabelsGroupRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId string
//   - labelsGroupId string
func (_e *LabelsGroupRepository_Expecter) Delete(ctx interface{}, organizationId interface{}, labelsGroupId interface{}) *LabelsGroupRepository_Delete_Call {
	return &LabelsGroupRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, organizationId, labelsGroupId)}
}

func (_c *LabelsGroupRepository_Delete_Call) Run(run func(ctx context.Context, organizationId string, labelsGroupId string)) *LabelsGroupRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *LabelsGroupRepository_Delete_Call) Return(_a0 error) *LabelsGroupRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LabelsGroupRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *LabelsGroupRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, organizationId, labelsGroupId
func (_m *LabelsGroupRepository) Get(ctx context.Context, organizationId string, labelsGroupId string) (*labels_group.LabelsGroup, error) {
	ret := _m.Called(ctx, organizationId, labelsGroupId)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *labels_group.LabelsGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*labels_group.LabelsGroup, error)); ok {
		return rf(ctx, organizationId, labelsGroupId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *labels_group.LabelsGroup); ok {
		r0 = rf(ctx, organizationId, labelsGroupId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*labels_group.LabelsGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, organizationId, labelsGroupId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LabelsGroupRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type LabelsGroupRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId string
//   - labelsGroupId string
func (_e *LabelsGroupRepository_Expecter) Get(ctx interface{}, organizationId interface{}, labelsGroupId interface{}) *LabelsGroupRepository_Get_Call {
	return &LabelsGroupRepository_Get_Call{Call: _e.mock.On("Get", ctx, organizationId, labelsGroupId)}
}

func (_c *LabelsGroupRepository_Get_Call) Run(run func(ctx context.Context, organizationId string, labelsGroupId string)) *LabelsGroupRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *LabelsGroupRepository_Get_Call) Return(_a0 *labels_group.LabelsGroup, _a1 error) *LabelsGroupRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LabelsGroupRepository_Get_Call) RunAndReturn(run func(context.Context, string, string) (*labels_group.LabelsGroup, error)) *LabelsGroupRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, organizationId, labelsGroupId, request
func (_m *LabelsGroupRepository) Update(ctx context.Context, organizationId string, labelsGroupId string, request labels_group.UpsertRequest) (*labels_group.LabelsGroup, error) {
	ret := _m.Called(ctx, organizationId, labelsGroupId, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *labels_group.LabelsGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, labels_group.UpsertRequest) (*labels_group.LabelsGroup, error)); ok {
		return rf(ctx, organizationId, labelsGroupId, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, labels_group.UpsertRequest) *labels_group.LabelsGroup); ok {
		r0 = rf(ctx, organizationId, labelsGroupId, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*labels_group.LabelsGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, labels_group.UpsertRequest) error); ok {
		r1 = rf(ctx, organizationId, labelsGroupId, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LabelsGroupRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type LabelsGroupRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId string
//   - labelsGroupId string
//   - request labels_group.UpsertRequest
func (_e *LabelsGroupRepository_Expecter) Update(ctx interface{}, organizationId interface{}, labelsGroupId interface{}, request interface{}) *LabelsGroupRepository_Update_Call {
	return &LabelsGroupRepository_Update_Call{Call: _e.mock.On("Update", ctx, organizationId, labelsGroupId, request)}
}

func (_c *LabelsGroupRepository_Update_Call) Run(run func(ctx context.Context, organizationId string, labelsGroupId string, request labels_group.UpsertRequest)) *LabelsGroupRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(labels_group.UpsertRequest))
	})
	return _c
}

func (_c *LabelsGroupRepository_Update_Call) Return(_a0 *labels_group.LabelsGroup, _a1 error) *LabelsGroupRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LabelsGroupRepository_Update_Call) RunAndReturn(run func(context.Context, string, string, labels_group.UpsertRequest) (*labels_group.LabelsGroup, error)) *LabelsGroupRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewLabelsGroupRepository creates a new instance of LabelsGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLabelsGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LabelsGroupRepository {
	mock := &LabelsGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
