// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_test

import (
	context "context"

	member "github.com/qovery/terraform-provider-qovery/internal/domain/member"
	mock "github.com/stretchr/testify/mock"
)

// OrganizationMemberRepository is an autogenerated mock type for the Repository type
type OrganizationMemberRepository struct {
	mock.Mock
}

type OrganizationMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrganizationMemberRepository) EXPECT() *OrganizationMemberRepository_Expecter {
	return &OrganizationMemberRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, organizationID, request
func (_m *OrganizationMemberRepository) Create(ctx context.Context, organizationID string, request member.InviteRequest) (*member.Member, error) {
	ret := _m.Called(ctx, organizationID, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *member.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, member.InviteRequest) (*member.Member, error)); ok {
		return rf(ctx, organizationID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, member.InviteRequest) *member.Member); ok {
		r0 = rf(ctx, organizationID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*member.Member)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, member.InviteRequest) error); ok {
		r1 = rf(ctx, organizationID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrganizationMemberRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrganizationMemberRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - request member.InviteRequest
func (_e *OrganizationMemberRepository_Expecter) Create(ctx interface{}, organizationID interface{}, request interface{}) *OrganizationMemberRepository_Create_Call {
	return &OrganizationMemberRepository_Create_Call{Call: _e.mock.On("Create", ctx, organizationID, request)}
}

func (_c *OrganizationMemberRepository_Create_Call) Run(run func(ctx context.Context, organizationID string, request member.InviteRequest)) *OrganizationMemberRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(member.InviteRequest))
	})
	return _c
}

func (_c *OrganizationMemberRepository_Create_Call) Return(_a0 *member.Member, _a1 error) *OrganizationMemberRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationMemberRepository_Create_Call) RunAndReturn(run func(context.Context, string, member.InviteRequest) (*member.Member, error)) *OrganizationMemberRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, organizationID, email
func (_m *OrganizationMemberRepository) Delete(ctx context.Context, organizationID string, email string) error {
	ret := _m.Called(ctx, organizationID, email)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, organizationID, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrganizationMemberRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type OrganizationMemberRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - email string
func (_e *OrganizationMemberRepository_Expecter) Delete(ctx interface{}, organizationID interface{}, email interface{}) *OrganizationMemberRepository_Delete_Call {
	return &OrganizationMemberRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, organizationID, email)}
}

func (_c *OrganizationMemberRepository_Delete_Call) Run(run func(ctx context.Context, organizationID string, email string)) *OrganizationMemberRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *OrganizationMemberRepository_Delete_Call) Return(_a0 error) *OrganizationMemberRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrganizationMemberRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *OrganizationMemberRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, organizationID, email
func (_m *OrganizationMemberRepository) Get(ctx context.Context, organizationID string, email string) (*member.Member, error) {
	ret := _m.Called(ctx, organizationID, email)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *member.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*member.Member, error)); ok {
		return rf(ctx, organizationID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *member.Member); ok {
		r0 = rf(ctx, organizationID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*member.Member)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, organizationID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrganizationMemberRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrganizationMemberRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - email string
func (_e *OrganizationMemberRepository_Expecter) Get(ctx interface{}, organizationID interface{}, email interface{}) *OrganizationMemberRepository_Get_Call {
	return &OrganizationMemberRepository_Get_Call{Call: _e.mock.On("Get", ctx, organizationID, email)}
}

func (_c *OrganizationMemberRepository_Get_Call) Run(run func(ctx context.Context, organizationID string, email string)) *OrganizationMemberRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *OrganizationMemberRepository_Get_Call) Return(_a0 *member.Member, _a1 error) *OrganizationMemberRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationMemberRepository_Get_Call) RunAndReturn(run func(context.Context, string, string) (*member.Member, error)) *OrganizationMemberRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, organizationID, email, request
func (_m *OrganizationMemberRepository) Update(ctx context.Context, organizationID string, email string, request member.UpdateRoleRequest) (*member.Member, error) {
	ret := _m.Called(ctx, organizationID, email, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *member.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, member.UpdateRoleRequest) (*member.Member, error)); ok {
		return rf(ctx, organizationID, email, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, member.UpdateRoleRequest) *member.Member); ok {
		r0 = rf(ctx, organizationID, email, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*member.Member)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, member.UpdateRoleRequest) error); ok {
		r1 = rf(ctx, organizationID, email, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrganizationMemberRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type OrganizationMemberRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - email string
//   - request member.UpdateRoleRequest
func (_e *OrganizationMemberRepository_Expecter) Update(ctx interface{}, organizationID interface{}, email interface{}, request interface{}) *OrganizationMemberRepository_Update_Call {
	return &OrganizationMemberRepository_Update_Call{Call: _e.mock.On("Update", ctx, organizationID, email, request)}
}

func (_c *OrganizationMemberRepository_Update_Call) Run(run func(ctx context.Context, organizationID string, email string, request member.UpdateRoleRequest)) *OrganizationMemberRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(member.UpdateRoleRequest))
	})
	return _c
}

func (_c *OrganizationMemberRepository_Update_Call) Return(_a0 *member.Member, _a1 error) *OrganizationMemberRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrganizationMemberRepository_Update_Call) RunAndReturn(run func(context.Context, string, string, member.UpdateRoleRequest) (*member.Member, error)) *OrganizationMemberRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrganizationMemberRepository creates a new instance of OrganizationMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationMemberRepository {
	mock := &OrganizationMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
