// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_test

import (
	context "context"

	terraformservice "github.com/qovery/terraform-provider-qovery/internal/domain/terraformservice"
	mock "github.com/stretchr/testify/mock"
)

// TerraformServiceRepository is an autogenerated mock type for the Repository type
type TerraformServiceRepository struct {
	mock.Mock
}

type TerraformServiceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TerraformServiceRepository) EXPECT() *TerraformServiceRepository_Expecter {
	return &TerraformServiceRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, environmentID, request
func (_m *TerraformServiceRepository) Create(ctx context.Context, environmentID string, request terraformservice.UpsertRepositoryRequest) (*terraformservice.TerraformService, error) {
	ret := _m.Called(ctx, environmentID, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *terraformservice.TerraformService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, terraformservice.UpsertRepositoryRequest) (*terraformservice.TerraformService, error)); ok {
		return rf(ctx, environmentID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, terraformservice.UpsertRepositoryRequest) *terraformservice.TerraformService); ok {
		r0 = rf(ctx, environmentID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*terraformservice.TerraformService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, terraformservice.UpsertRepositoryRequest) error); ok {
		r1 = rf(ctx, environmentID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TerraformServiceRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TerraformServiceRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - environmentID string
//   - request terraformservice.UpsertRepositoryRequest
func (_e *TerraformServiceRepository_Expecter) Create(ctx interface{}, environmentID interface{}, request interface{}) *TerraformServiceRepository_Create_Call {
	return &TerraformServiceRepository_Create_Call{Call: _e.mock.On("Create", ctx, environmentID, request)}
}

func (_c *TerraformServiceRepository_Create_Call) Run(run func(ctx context.Context, environmentID string, request terraformservice.UpsertRepositoryRequest)) *TerraformServiceRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(terraformservice.UpsertRepositoryRequest))
	})
	return _c
}

func (_c *TerraformServiceRepository_Create_Call) Return(_a0 *terraformservice.TerraformService, _a1 error) *TerraformServiceRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TerraformServiceRepository_Create_Call) RunAndReturn(run func(context.Context, string, terraformservice.UpsertRepositoryRequest) (*terraformservice.TerraformService, error)) *TerraformServiceRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, terraformServiceID
func (_m *TerraformServiceRepository) Delete(ctx context.Context, terraformServiceID string) error {
	ret := _m.Called(ctx, terraformServiceID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, terraformServiceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TerraformServiceRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TerraformServiceRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - terraformServiceID string
func (_e *TerraformServiceRepository_Expecter) Delete(ctx interface{}, terraformServiceID interface{}) *TerraformServiceRepository_Delete_Call {
	return &TerraformServiceRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, terraformServiceID)}
}

func (_c *TerraformServiceRepository_Delete_Call) Run(run func(ctx context.Context, terraformServiceID string)) *TerraformServiceRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TerraformServiceRepository_Delete_Call) Return(_a0 error) *TerraformServiceRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TerraformServiceRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *TerraformServiceRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, terraformServiceID, advancedSettingsJsonFromState, isTriggeredFromImport
func (_m *TerraformServiceRepository) Get(ctx context.Context, terraformServiceID string, advancedSettingsJsonFromState string, isTriggeredFromImport bool) (*terraformservice.TerraformService, error) {
	ret := _m.Called(ctx, terraformServiceID, advancedSettingsJsonFromState, isTriggeredFromImport)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *terraformservice.TerraformService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*terraformservice.TerraformService, error)); ok {
		return rf(ctx, terraformServiceID, advancedSettingsJsonFromState, isTriggeredFromImport)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *terraformservice.TerraformService); ok {
		r0 = rf(ctx, terraformServiceID, advancedSettingsJsonFromState, isTriggeredFromImport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*terraformservice.TerraformService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, terraformServiceID, advancedSettingsJsonFromState, isTriggeredFromImport)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TerraformServiceRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TerraformServiceRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - terraformServiceID string
//   - advancedSettingsJsonFromState string
//   - isTriggeredFromImport bool
func (_e *TerraformServiceRepository_Expecter) Get(ctx interface{}, terraformServiceID interface{}, advancedSettingsJsonFromState interface{}, isTriggeredFromImport interface{}) *TerraformServiceRepository_Get_Call {
	return &TerraformServiceRepository_Get_Call{Call: _e.mock.On("Get", ctx, terraformServiceID, advancedSettingsJsonFromState, isTriggeredFromImport)}
}

func (_c *TerraformServiceRepository_Get_Call) Run(run func(ctx context.Context, terraformServiceID string, advancedSettingsJsonFromState string, isTriggeredFromImport bool)) *TerraformServiceRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *TerraformServiceRepository_Get_Call) Return(_a0 *terraformservice.TerraformService, _a1 error) *TerraformServiceRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TerraformServiceRepository_Get_Call) RunAndReturn(run func(context.Context, string, string, bool) (*terraformservice.TerraformService, error)) *TerraformServiceRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, environmentID
func (_m *TerraformServiceRepository) List(ctx context.Context, environmentID string) ([]terraformservice.TerraformService, error) {
	ret := _m.Called(ctx, environmentID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []terraformservice.TerraformService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]terraformservice.TerraformService, error)); ok {
		return rf(ctx, environmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []terraformservice.TerraformService); ok {
		r0 = rf(ctx, environmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]terraformservice.TerraformService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, environmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TerraformServiceRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TerraformServiceRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - environmentID string
func (_e *TerraformServiceRepository_Expecter) List(ctx interface{}, environmentID interface{}) *TerraformServiceRepository_List_Call {
	return &TerraformServiceRepository_List_Call{Call: _e.mock.On("List", ctx, environmentID)}
}

func (_c *TerraformServiceRepository_List_Call) Run(run func(ctx context.Context, environmentID string)) *TerraformServiceRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TerraformServiceRepository_List_Call) Return(_a0 []terraformservice.TerraformService, _a1 error) *TerraformServiceRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TerraformServiceRepository_List_Call) RunAndReturn(run func(context.Context, string) ([]terraformservice.TerraformService, error)) *TerraformServiceRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, terraformServiceID, request
func (_m *TerraformServiceRepository) Update(ctx context.Context, terraformServiceID string, request terraformservice.UpsertRepositoryRequest) (*terraformservice.TerraformService, error) {
	ret := _m.Called(ctx, terraformServiceID, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *terraformservice.TerraformService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, terraformservice.UpsertRepositoryRequest) (*terraformservice.TerraformService, error)); ok {
		return rf(ctx, terraformServiceID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, terraformservice.UpsertRepositoryRequest) *terraformservice.TerraformService); ok {
		r0 = rf(ctx, terraformServiceID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*terraformservice.TerraformService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, terraformservice.UpsertRepositoryRequest) error); ok {
		r1 = rf(ctx, terraformServiceID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TerraformServiceRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TerraformServiceRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - terraformServiceID string
//   - request terraformservice.UpsertRepositoryRequest
func (_e *TerraformServiceRepository_Expecter) Update(ctx interface{}, terraformServiceID interface{}, request interface{}) *TerraformServiceRepository_Update_Call {
	return &TerraformServiceRepository_Update_Call{Call: _e.mock.On("Update", ctx, terraformServiceID, request)}
}

func (_c *TerraformServiceRepository_Update_Call) Run(run func(ctx context.Context, terraformServiceID string, request terraformservice.UpsertRepositoryRequest)) *TerraformServiceRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(terraformservice.UpsertRepositoryRequest))
	})
	return _c
}

func (_c *TerraformServiceRepository_Update_Call) Return(_a0 *terraformservice.TerraformService, _a1 error) *TerraformServiceRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TerraformServiceRepository_Update_Call) RunAndReturn(run func(context.Context, string, terraformservice.UpsertRepositoryRequest) (*terraformservice.TerraformService, error)) *TerraformServiceRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewTerraformServiceRepository creates a new instance of TerraformServiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTerraformServiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TerraformServiceRepository {
	mock := &TerraformServiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
